### ISSUE TITLE
Schema section

### ISSUE THREAD

**Issue by rgregg** [apiaryio/api-blueprint#112]
Are there more details about what content goes in the Schema section in a Payload? The documentation just says "Specifies a validation schema for the HTTP message-body" but doesn't provide any examples.

**Comment by gondo** [comment]
@zdne wouldn't it be better to update the documentation rather than point people to stackoverflow?

**Comment by zdne** [comment]
@gondo you are indeed correct! @kylef is working on a new set of tutorials that will definitely cover this. Thanks for pointing this one out.

**Comment by gondo** [comment]
@zdne cool.

in the meantime, this might help someone, or someone might help me :) http://stackoverflow.com/questions/28221984/how-to-create-nested-schema

**Comment by zdne** [comment]
Thanks for sharing! :+1:
