### ISSUE TITLE
Parameters: Description of enumeration elements

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/api-blueprint#119]
Currently, only

    + Values
        + `A`
        + `B`
        + `C`

works. However, people want ([1](https://stackoverflow.com/questions/25739360/how-to-add-value-description-with-api-blueprint), [2](https://stackoverflow.com/questions/25092263/how-to-add-description-to-the-value-of-the-query-attribute)) to document such values separately. Let's say, they want something like

    + Values
        + `A` ... means something
        + `B` ... means something else
        + `C` ... means something completely different

(Just made up the syntax, please do not take it as a real proposal - I assume we need to evaluate the feature request first.)

**Comment by pksunkara** [comment]
When we align parameters syntax to MSON, this should be achieved by

```md
- country (enum[string])
    - `CZE` - Czech Republic
    - `IND` - India
```

**Comment by zdne** [comment]
RFC proposal of syntax addressing this issue: https://github.com/apiaryio/api-blueprint-rfcs/pull/3. 

Please track and comment on the RFC.

Thank you!
