### ISSUE TITLE
Multiple problems in examples/10. Data Structures.md

### ISSUE THREAD

**Issue by jrep** [apiaryio/api-blueprint#145]
`snowcrash -u 10.\ Data\ Structures.md ` reports warnings, and apparently silently ignores the *Data Structures* example.

## Warnings

```
warning: (5)  ignoring unrecognized block; line 42, column 5 - line 43, column 1; line 44, column 5 - line 44, column 98
warning: (3)  no parameters specified, expected a nested list of parameters, one parameter per list item; line 40, column 1 - line 45, column 1
```

## Silent Ignorance

I'm trying to write my own Data Structure. Mine also is silently ignored. Is this a deficit in snowcrash? How can I validate my blueprint?

## Configuration

[Gist](https://gist.github.com/jrep/b3a20f7750922f3db491) containing the file I see and the output.

I'm looking at `api-blueprint` repo, branch `zdne/attributes-description`, file `examples/10. Data Structures.md`, latest change

```
commit 9be1404c6d9abe27e4ce9c000307fe2c037d6795
Author: Z <z@apiary.io>
Date:   Tue Nov 25 13:02:49 2014 +0100
```

I'm using repo `snowcrash`, branch `shared/mson-integration`, latest change

```
commit 91028c91f270338173306aff255a01c53e0edfcf
Merge: 4bda175 817b1cd
Author: Z <zdenek@me.com>
Date:   Tue Dec 23 11:29:13 2014 +0100
```

**Comment by zdne** [comment]
Hey @jrep thanks for the report! 

Re _Warnings_ – @pksunkara can you please look into it and let us know where the issues is? 

Re _Silent Ignorance_ – we are currently not exporting the Data Structure AST in the serialization format. The reason for this is concern with the growing AST complexity as discussed [here](https://github.com/apiaryio/api-blueprint-ast/pull/14#issuecomment-68152446). I expect us to solve this and fully expose the data structures AST subtree in the course of next two weeks.

**Comment by zdne** [comment]
poke @pksunkara

**Comment by pksunkara** [comment]
Yes, I have this in my inbox, I am just waiting to finalise AST changes PR.

**Comment by pksunkara** [comment]
Hey @jrep It silently ignores the data structures because they weren't serialised by the time you were working with the `shared/mson-integration` branch. But now, they are working since we recently merged the serialisation for them.

#146 takes care of the warnings you are getting.
