### ISSUE TITLE
Allow HTTP method along with Resource name and uri

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/api-blueprint#151]
I have a resource which has only action. Currently, I need to do the following:

```
## Verification [/users/{user}/verify/{token}]
### Verify the user [GET]
+ Response 201
```

I think we should allow a shortcut for this (whenever a resource has one action only)

```
## Verify the user [GET /users/{user}/verify/{token}]
+ Response 201
```

**Comment by fosrias** [comment]
Wont that get solved in upcoming functionality to add path to action @zdne?

**Comment by zdne** [comment]
Yup, see here https://github.com/apiaryio/api-blueprint/issues/88. Closing as duplicate
