### ISSUE TITLE
API call failed in Console when using '+' or '-'

### ISSUE THREAD

**Issue by sgriffiths** [apiaryio/api-blueprint#157]
See screenshot:

![2015-02-23_14h29_53](https://cloud.githubusercontent.com/assets/1687746/6322787/d75f3674-bb68-11e4-8994-81cd09fe5406.png)

Doing a Call Resourse against the mock server fails when using the '+' or '-' characters in the parameter fields.

**Comment by pksunkara** [comment]
@sgriffiths Could you try using `GREATER%2BBRISBANE-QLD`? That said, please note that is a repository for the API Blueprint spec. The above issue is an apiary documentation issue. Please send an email to apiary support from the next time. Thanks.

@Baggz Are we encoding the values given for URI parameters?

**Comment by sgriffiths** [comment]
Hi, 

That works when using "GREATER%2BBRISBANE-QLD". Will go through support next time.
