### ISSUE TITLE
Explicit way to mark attribute as optional

### ISSUE THREAD

**Issue by varas** [apiaryio/api-blueprint#166]
I think it would be very helpful to mark a resource atributte as optional *explicitly*, don't you?

**Comment by honzajavorek** [comment]
If you refer to the new [MSON](https://github.com/apiaryio/mson) syntax as promoted in #135, marking attribute as optional is [already in the spec](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#353-type-attribute) and as far as I know, it is already supported also by parser.

**Comment by varas** [comment]
I've reading the docs for a while and I didn't know about MSON, thanks!

So the way should be to write a MSON for the object and explicit its `required` attributes (as optional is the default), is it?

**Comment by zdne** [comment]
> So the way to go should be to write a MSON for the object and explicit its required attributes (as optional is the default), is it?

Correct! But you can describe just one of the attributes. Generally the MSON / attributes description is about what you MAY get and if you get it what it means not what you WILL get (unless it is required obviously)

**Comment by varas** [comment]
Great, thank you!
