### ISSUE TITLE
Get json response according to uri parameter value

### ISSUE THREAD

**Issue by suleymanccelik** [apiaryio/api-blueprint#176]
Hi everyone,

How can I achieve to get json response according to uri parameter value? If p is equal to Y, I want to get first json body. But there is no p field in json body. If p is equal to X,  I want to get second json body. I am using drakov as mock server. When I start drakov mock server, Both localhost:3000/api.php?p=Y and localhost:3000/api.php?p=X returns first json body.

drakov url : https://www.npmjs.com/package/drakov

## GET /api.php?p=Y
+ Response 200 (application/json)

        { 
            json body
        }

## GET /api.php?p=X
+ Response 200 (application/json)

        {
             json body
        }

**Comment by zdne** [comment]
Hey @suleymanccelik at the moment there is no dedicated syntax to do this. The only way is to use response / request description with any Markdown formatted text of your liking. However this won't work for machine processing such as Drakov. However we plan to implement this syntax soon - see https://github.com/apiaryio/api-blueprint/issues/132

**Comment by suleymanccelik** [comment]
Thanks for reply @zdne. I follow your updates for related issues.

**Comment by zdne** [comment]
Closing as duplicate to #132
