### ISSUE TITLE
Allow port specification of host on endpoint definition

### ISSUE THREAD

**Issue by nkijak** [apiaryio/api-blueprint#180]
Trying to spec out an internal API map of services where each service is running on a specific port.  The hostname is the same.  

Tried to do something like `## Users [:9000/users]` but that causes the url for testing to become just the `HOST`. 
Also tried `### Create User [POST http://host:port/path]` but that causes the block to not be rendered at all.

**Comment by zdne** [comment]
@nkijak currently the only way to do this is to use `HOST: http://host:port` at the top of the blueprint. In other words you would need two blueprints for production and WIP APIs. 

Is this question – feature request – basically about supporting description of multiple APIs in one blueprint? 

possibly related to https://github.com/apiaryio/api-blueprint/issues/122

**Comment by nkijak** [comment]
Yes, the request is to allow port definitions or redefinition of the host in the single blueprint.

**Comment by zdne** [comment]
To be handled with #122
