### ISSUE TITLE
Problem with attribute values

### ISSUE THREAD

**Issue by jmdacruz** [apiaryio/api-blueprint#187]
I'm trying to define an attribute with a value that is a GUID, but I don't seem to find the way to properly express this:

+ Attributes (object)
    + uuid: 08ff7052-2e95-11e3-a1fc-000c294eede0 (guid) - Unique ID
    + date: 2014-07-14T12:03:20z (date) - A date

When doing the above, the parser seems to cut the definition on the first "-", which means that the first portion of the string is considered the example value (e.g., "08ff7052") and the second portion is considered to be part of the description (e.g., "2e95-11e3-a1fc-000c294eede0 (guid) - Unique ID")

I'm probably doing something wrong... can you point me in the right direction?

**Comment by kylef** [comment]
When a literal contains reserved characters such as `-` it needs to be wrapped in backticks. See [reserved characters & keywords](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords).

It should look something like the following:

+ Attributes (object)
    + uuid: `08ff7052-2e95-11e3-a1fc-000c294eede0` (guid) - Unique ID
    + date: `2014-07-14T12:03:20z` (date) - A date

**Comment by jmdacruz** [comment]
Thanks, that did part of the trick... but it also seems I can't define custom data types (e.g., "guid" or "date"), since I also get an error when doing that.

**Comment by kylef** [comment]
@jmdacruz You would need to declare them in the [`Data Structures`](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-data-structures) section. Such as the following:

```markdown
+ Attributes (object)
    + uuid: `08ff7052-2e95-11e3-a1fc-000c294eede0` (guid) - Unique ID
    + date: `2014-07-14T12:03:20z` (date) - A date
    
# Data Structures
## guid (string)
## date (string)
```

**Comment by jmdacruz** [comment]
Doh! thanks, I had missed that. Is there a way to attach regular expressions to these user-defined data structures? If not, it might be a nice-to-have.

**Comment by honzajavorek** [comment]
@jmdacruz You could provide custom [Schema section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-schema-section). In the future, we consider to have [Validations](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#46-validations) right in the user-defined data structures.

**Comment by jmdacruz** [comment]
Great, thanks!
