### ISSUE TITLE
Referenced Payloads

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint#19]
Provide the ability to define arbitrary payloads that can be referenced later (similar to the concept of resource object).

**Comment by vhordejcuk** [comment]
Referencing sounds great. In situations where resource model is unapplicable.

**Comment by zdne** [comment]
As per my comments on #47 this feature is covered partially by the introduction of #25 and it will be covered completely when #286 and #20 is implemented. Closing this issue.
