### ISSUE TITLE
Attribute doesn't parse correctly with dash in the value

### ISSUE THREAD

**Issue by tigerpenguin** [apiaryio/api-blueprint#192]
The `Attributes` parser seems to eagerly match the first dash and breaks it up into `description` and `value`.

```
+ Attributes
    + blog_url: https://www.trunkclub.com/blog/is-the-hoodie-the-new-power-suit (string, required) - Blog url
```

Expected:

Name | Type | Required | Description | Value
---------|--------|--------------|-----------------|--------
blog_url | string | required | Blog url | https://www.trunkclub.com/blog/is-the-hoodie-the-new-power-suit

Actual:

Name | Type | Required | Description | Value
---------|--------|--------------|-----------------|--------
blog_url | | optional | the-hoodie-the-new-power-suit (string, required) - Blog url | https://www.trunkclub.com/blog/is

**Comment by zdne** [comment]
@tigerpenguin please use back tick to escape values with reserved characters:


```markdown
+ Attributes
    + blog_url: `https://www.trunkclub.com/blog/is-the-hoodie-the-new-power-suit` (string, required) - Blog url
```


See [MSON reserved characters](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords)

**Comment by tigerpenguin** [comment]
Thanks! @zdne
