### ISSUE TITLE
Relation type has to be lowercased 

### ISSUE THREAD

**Issue by Baggz** [apiaryio/api-blueprint#193]
```Markdown
### List all questions [GET]

+ Relation: Questions
```

If I specify relation type as `Questions` (capital `Q`), it's **rendered as a list item**.

```Markdown
### List all questions [GET]

+ Relation: questions
```

If I specify relation type as `questions` (lowercased `q`), it's rendered correctly.

Is this expected behaviour?

Thanks for the clarification!

**Comment by kylef** [comment]
From my understand of [RFC 5988](https://tools.ietf.org/html/rfc5988) it isn't *required* but they *should* be lower case:

> "Because of this, all lowercase URIs SHOULD be used for extension relations." -- 4.2.  Extension Relation Types

**Comment by zdne** [comment]
To be fixed in:  https://github.com/apiaryio/snowcrash/issues/320

**Comment by pksunkara** [comment]
Fixed by https://github.com/apiaryio/snowcrash/commit/cb9f9e59d54ccb8d62a7a197ae760a2a898e21ae

**Comment by zdne** [comment]
@pksunkara Has this been released? If so where? Fury? Apiary.io? I am afraid since this issues is coming from Apiary it shouldn't be considered fixed until it is released...

**Comment by pksunkara** [comment]
Oh sorry. Working on releasing it.
