### ISSUE TITLE
Named resource with method and uri

### ISSUE THREAD

**Issue by LinusU** [apiaryio/api-blueprint#196]
I'm trying to write a quick start guide in addition to the api specification that will help new users to quickly get started. I'm running into problems when trying to name the steps in the tutorial.

This is the blueprint:

```apib
# Group Quick start

## Create user [POST /users]

The first thing we need to do is to add a user that we can later log in as. Do
this by sending a POST request with the relevant details.

+ Request
  + Headers
    Content-Type: application/json
  + Body
    { "username": "Linus", "password": "test" }

+ Response 201
  + Headers
    Location: /user/1337

## Log in as the user [POST /session]

We can now log in as the user we created. This is accomplished by creating a new
session with the relevant login details.

+ Request
  + Headers
    Content-Type: application/json
  + Body
    { "username": "Linus", "password": "test" }

+ Response 201
  + Headers
    X-Token: djksaldjaklsj894ut93
    Location: /session/8493248
```

The problem is `## Create user [POST /users]` and `## Log in as the user [POST /session]`.

For some reson they gets parsed as a text block instead of a resource with one action. If I remove the name I gave them, and only add the method + uri, it works as expected. (i.e. `## POST /users`)

Shouldn't this work?

**Comment by zdne** [comment]
Unfortunately no :( Currently only actions under a resource can be named – the idea was to encourage resource oriented architectures instead of just writing endpoints. 

However what you are suggesting is making a sense (and I actually really like it). We are looking at "scenario" support as a part of testing – https://github.com/apiaryio/api-blueprint/issues/21 And this is somewhat related. 

What do you think? I would suggest to have a look at the scenarios in #21 and refine a syntax proposal from this. Does it make sense. Or is it really just "named" endpoints that would help here and scenarios are overkill?

**Comment by LinusU** [comment]
Hmm, as far as I understood the scope of API Blueprint it's not only meant for REST APIs. For example the website says "API Documentation with powerful tooling" and dosen't mention REST at all.

If this is the case I think it's very bad to "encourage resource oriented architectures" as some APIs just aren't fit for that architecture. I think that API Blueprint should treat every api design as equals and not try and nudge people against one of them.

Scenarios is very cool, but it seems very testing oriented. While this is great for my needs, I'm not sure that API Blueprint should bend that much towards testing. I think that the approach that I took in [LinusU/mocha-api-blueprint-example](https://github.com/LinusU/mocha-api-blueprint-example) is more of a documentation first approach.

It documents guides that is intended for the user to follow, that also have the benefit of being testable. Scenarios seems more like they are only meant for testing, but I might be getting it wrong. What are your thoughts on this?

**Comment by zdne** [comment]
> For example the website says "API Documentation with powerful tooling" and dosen't mention REST at all.

That is fair point. However – strictly speaking – most of the APIs nowadays are not REST at all. Also the APIs could be anything really not just on distributed system (e.g interface between two libraries). 

Either way – putting any disputes about copy aside – I think introducing syntax to allow add human readable name to an endpoint like: 

```apib
## Create user [POST /users]
```

makes a lot of sense. Even without full-fledeged support for scenarios. Maybe this could be a building block for it. 

Would you care to propose a PR to change this in the Specification and/or add examples for it?

**Comment by LinusU** [comment]
I think that would be a very good first step! I'll try to send in a pull request tomorrow :)

**Comment by zdne** [comment]
Great! Any chance you can do it in the C++ code too? :dancer:

**Comment by LinusU** [comment]
Working on the C++ code now :raising_hand:

**Comment by LinusU** [comment]
Would love some help over in apiaryio/snowcrash#332 :penguin:

**Comment by zdne** [comment]
Thanks @LinusU! See my reply there.

**Comment by zdne** [comment]
This was released in [1A9](https://github.com/apiaryio/api-blueprint/releases/tag/format-1A9) thanks to you @LinusU !
