### ISSUE TITLE
Problems using custom headings

### ISSUE THREAD

**Issue by NobodysNightmare** [apiaryio/api-blueprint#199]
Hello,

I am writing because I am not sure anymore if I understood the very basics of API blueprint and thus I either found a bug (and have to find out where that would best be posted) or I realized I am using API Blueprint wrong.

My issue came up after updating my installed version of [Aglio](https://github.com/danielgtaylor/aglio) after a long time and it started throwing lots of warnings onto me and would render some parts not like I'd expect.

# How we currently use API Blueprint

For reference: [our blueprint can be found on GitHub](https://github.com/opf/openproject/blob/dev/doc/apiv3-documentation.apib)

We intend to write the whole documentation for our new API in API Blueprint. This means there is some [introductory part](https://github.com/opf/openproject/blob/09e86e3cd8317994dafa18faf3c7a0772ecfd7d7/doc/apiv3-documentation.apib#L5-L276) that is pretty much pure Markdown, followed by the structured part that employs the syntax and semantics of API Blueprint.

**First Question**: Is API Blueprint even intended to be used that way? That is: Multiple paragraphs and sections of pure markdown, without any (formal) resources being described.

Note: We have lots of headlines (`# Foo` and `## Bar`) and two groups (`# Group foo`) before the first formal resource definition.

# What broke our blueprint

The thing that worked before (at least in aglio `1.16.1`) and would now start to [generate warnings](https://gist.github.com/NobodysNightmare/f5c9a5b7b4c5d01190a1) were very specific headlines:
````
## Properties
````
We use this headline over (handcrafted) property tables. In the introduction as well as when describing resources, e.g. [here](https://github.com/opf/openproject/blob/09e86e3cd8317994dafa18faf3c7a0772ecfd7d7/doc/apiv3-documentation.apib#L96-L103) or [here](https://github.com/opf/openproject/blob/09e86e3cd8317994dafa18faf3c7a0772ecfd7d7/doc/apiv3-documentation.apib#L1079-L1086).

After replacing those with

````
## Local Properties
````

the warnings disappear and rendering returns to normal.

**Second Question**: Is `## Properties` a reserved headline/keyword? I could not find anything in the [specification](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md).

# Disclaimer

I realize that the problems I am seeing, could well be related to the tools I am using (e.g. aglio). However, I wanted to first make sure that the way I am using API Blueprint is by any means "correct" and that I should be able to expect things to work beforehand.

Thanks for taking the time to review my issue :cat2:

**Comment by klokane** [comment]
In short `Properties` is reserved word for [MSON](https://github.com/apiaryio/mson) which is now used for data structures definitions

Another valid solution is enclose keyword into backticks like this:

```md
### `Properties` 
```

If you want to clear something more, dont hesiatate ask.

**Comment by NobodysNightmare** [comment]
Thank you for your quick response.

So I assume, that it is fine to have extended parts of plain text in the same document. If that is true I have no further questions for the moment :smile: 

Best regards!

**Comment by honzajavorek** [comment]
> is fine to have extended parts of plain text in the same document

@NobodysNightmare Yes, that's perfectly fine!
