### ISSUE TITLE
Need tool to create api blueprint document from comments in multiple files

### ISSUE THREAD

**Issue by nbasov** [apiaryio/api-blueprint#200]
Hello! I really like api blueprint, but one thing stops me to use it in my projects. Could you please tell if there is a tool to create final api blueprint document from multiple files (from comments within each file)? Like apiDoc (http://apidocjs.com) already did.

Sure I can grep comments from files and concatenate them. But in this case i will need to support files order somehow (0_file1.js, 1_file2.js, etc).

**Comment by zdne** [comment]
@nbasov there are many, but my favorite is https://github.com/jamesramsay/hercule

**Comment by zdne** [comment]
@nbasov another good example would be here https://github.com/the-grid/apidocs. 

Please check it out and feel free to comment / reopen if needed.
