### ISSUE TITLE
underscore in parameter/attribute descriptions (MSON syntax)

### ISSUE THREAD

**Issue by rcrooks** [apiaryio/api-blueprint#202]
underscores in param descriptions thrown the parser in various ways. I've been able to work around cases that actually generate syntax errors. Here's non-fatal one that's problematic though - have a link in the description and need it to open in a different tab/window, so using <a target="_blank" ... That doesn't generate a syntax error, but does mess up syntax highlighting in Sublime Text, Github, etc... For example, see what happens after line 126 here: https://github.com/BrightcoveLearning/cms-api/blob/master/apiary.apib

Hardly a show-stopper, but annoying -- would be nice if there were some way to slip this past the parser

**Comment by pksunkara** [comment]
@danielgtaylor I think this is a bug in our syntax highlighter.

**Comment by danielgtaylor** [comment]
You're right. I've added a corresponding issues to the Sublime Text plugin, which is where the master syntax lives. See the link above this comment. I'm locking this issue - please post any future comments to the Sublime Text plugin issue.

**Comment by kylef** [comment]
I'm going to close this issue since it's moved to https://github.com/apiaryio/api-blueprint-sublime-plugin/issues/23.
