### ISSUE TITLE
hyphenated attribute name not parsed correctly

### ISSUE THREAD

**Issue by rcrooks** [apiaryio/api-blueprint#208]
Not sure if this issue belongs here or in SnowCrash. If you have an attribute like this:
+ capture-images (boolean, optional) - whether poster and thumbnail should be captured during transcoding

the attribute name is rendered as "capture" and everything following is treated as a description
sample rendering here: http://docs.dynamicingestapi.apiary.io/#reference/create-ingest-request/post-to-make-request/post

**Comment by kylef** [comment]
@rcrooks As per the MSON specification `-` is a reserved character and when used, you must wrap your string in backticks.

So you should use this instead:

```apib
+ `capture-images` (boolean, optional) - whether poster and thumbnail should be captured during transcoding
```

See [MSON reserved characters](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords)
