### ISSUE TITLE
Allow markdown linking in subsections

### ISSUE THREAD

**Issue by nathanielks** [apiaryio/api-blueprint#212]
I'd like to be able to link to other portions of the document or web pages when defining attributes and parameters, but currently the markdown formatted link is just displaying as text instead of link.

Example:
```
+ Attributes (object)
    + attribute: `` (object) - Blah Blah Blah. Refer to the [spec](http://jsonapi.org).
```

**Comment by zdne** [comment]
Hey @nathanielks, thanks for the feedback! Just to clarify by "is just displaying as text instead of link" you are referring to rendering the blueprint at Apiary.io – is that correct? If so this is a know issue – a proper support for rendering MSON at Apiary is in the making. See https://github.com/apiaryio/api-blueprint/issues/191

**Comment by Perni1984** [comment]
I confirm this is partially working (I have the Feature switch on for the new rendering), but it is broken for links that have reserved characters in them:

Works:

	+ Attributes (object)
		- vat_id: ATU99999999 (string) - VAT identification [number](https://en.wikipedia.org/wiki/)

Doesn't work:

	+ Attributes (object)
		- vat_id: ATU99999999 (string) - VAT identification [number](https://en.wikipedia.org/wiki/VAT_identification_number)

Also escaping doesn't help - doesn't work:

	+ Attributes (object)
		- vat_id: ATU99999999 (string) - `VAT identification [number](https://en.wikipedia.org/wiki/VAT_identification_number)`

**Comment by zdne** [comment]
Hey @Perni1984, 
  try to put `vat_id` into backticks. The underscore is reserved character in MSON, see https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#61-characters

**Comment by zdne** [comment]
with the backticks the MSON renders just fine for me.

**Comment by Perni1984** [comment]
@zdne: thanks. I feel dumb now ;-)

**Comment by zdne** [comment]
@Perni1984 oh, no need to! The user experience isn't the best there and we need to improve it

**Comment by pksunkara** [comment]
Please follow #191 to know the when the new rendered will be rolled out. I am closing this.
