### ISSUE TITLE
Support for custom authentication schemes

### ISSUE THREAD

**Issue by timb-pt** [apiaryio/api-blueprint#215]
I'm documenting a custom, preexisting authentication scheme that adds custom parameters to the query string and headers. How can I specify all of these without repeating myself for every API call?

**Comment by kylef** [comment]
@timb-pt While this isn't currently supported in API Blueprint, there is an open pull request with a proposal for how this would work, I'd suggest you take a look at #201 and please share any feedback you might have.

Duplicates #201 / #11.

**Comment by pksunkara** [comment]
Hey @timb-pt,

#201 deals with supporting popular authentication schemes. We also have plans to support Custom authentication schemes but they aren't described in #201 even though we proposed that PR with them in mind.

Would love to get some of your feedback on #201 and how to extend it to support Custom authentication schemes.

**Comment by timb-pt** [comment]
@kylef @pksunkara Thanks! I posted more information about my use case in in #201.

**Comment by zdne** [comment]
Refer to

RFC 0002: https://github.com/apiaryio/api-blueprint-rfcs/blob/master/draft/0002-authentication.md 
RFC 0003: https://github.com/apiaryio/api-blueprint-rfcs/blob/master/draft/0003-authentication-basic.md

**Comment by zdne** [comment]
Closing as duplicate to #11
