### ISSUE TITLE
Same response with different body objects depending on the presence of a query parameter

### ISSUE THREAD

**Issue by tsz662** [apiaryio/api-blueprint#217]
Hi,

I am quite new to API Blueprint and please forgive me for such novice questions.
(If they are duplicates of existing issues or have already been answered, please tell me where to look at.)

## Question 1

How can I describe a resource that changes the request body object (but with the same status code) depending on the presence of a certain query parameter, for example:
````
GET /api/images
````
returns the total number of images stored on the server:
````javascript
{"total" : 200}
````
and
````
GET /api/images?groups=mygroup
````
returns additional information about the number of images owned by the specified group, like so:
````javascript
{"total" : 200, "group" : 30}
````
## Question 2

How can I describe a resource that does the same as above but accepts form parameters instead of query parameters?

**Comment by pksunkara** [comment]
The feature you are requesting in the first question can be tracked at #58.

The answer to you second question is [Attributes section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section). Please keep in mind that MSON support is still in beta.

**Comment by tsz662** [comment]
Thank you for the quick response!
