### ISSUE TITLE
Attributes in Apiary are always shown as required

### ISSUE THREAD

**Issue by Saviio** [apiaryio/api-blueprint#218]
Hi Support Team：

I just wonder if I wrote a wrong syntax because I cannot get right attribute rendering.
Here's a part of md file.

```
### Insert Business Record[POST]
+ Attributes
    + OpenId: `OpenId` (required,string) 
    + CampaignName : `Campaign Name` (optional,string)
```
But the CampaignName field get wrong rendering, it still shown "Required", but I want "Optional". see this below.

![es](https://cloud.githubusercontent.com/assets/3467408/8428945/b208b1f6-1f55-11e5-885d-73f5f1fbccd4.png)

Can you help for this?

**Comment by pksunkara** [comment]
Hey @Saviio,

Can you link me the whole API Blueprint file? I would like test if it's an error in the parser or not. Thanks.

**Comment by kylef** [comment]
I've confirmed this is a bug in Apiary itself, and it's internally tracked at Apiary.

**Comment by XVincentX** [comment]
Hey @Saviio 
I just wanted to mention that we have deployed a fix for the issue you pointed out.

Could you please let me know if the thing is now working properly?

Feel free to reopen the issue if the problem still persists.

**Comment by Saviio** [comment]
Hi @XVincentX 

it doesn't seem to have any effect.

please have a look
![image](https://cloud.githubusercontent.com/assets/3467408/8503339/65ecfa78-21f0-11e5-885e-1e8a5bde7694.png)

and here's my test document : http://docs.test5005.apiary.io

**Comment by XVincentX** [comment]
@Saviio Could you please try again now?

**Comment by pksunkara** [comment]
I can confirm it's working now.

**Comment by Saviio** [comment]
@XVincentX 
@pksunkara 

Hi, It's worked, thank you :+1:
