### ISSUE TITLE
Incorrect parsing of attributes with underscores

### ISSUE THREAD

**Issue by tfedor** [apiaryio/api-blueprint#219]
There seems to be a bug with attribute rendering if they include underscore:

```
+ Attributes
    + grantType: authorization_code
    + grant_type: authorization_code
    + grant\_type: authorization\_code
```
Displays this:
![attributes](https://cloud.githubusercontent.com/assets/5072842/8441926/cdeee608-1f7b-11e5-8ae7-5d832cb05e56.png)

Is there another way how to escape characters or is this a bug?

**Comment by pksunkara** [comment]
Hey, If you read the MSON spec, you can see that `_` is a reserved character. Please use backticks to escape the whole word. Here is an example:

```
+ `grant_type`: `authorization_code`
```

**Comment by zdne** [comment]
Note there is a plan to improve the user experience around this https://github.com/apiaryio/api-blueprint/issues/210
