### ISSUE TITLE
Recursive Objects Support

### ISSUE THREAD

**Issue by wersoo** [apiaryio/api-blueprint#220]
Does API Blueprint (and Apiary.io as well) support self-referenced structures?
Currently I need to describe tree-alike structure and I'm doing it like this:

```apib
    ## Category (object)
    + categoryId: `321` (number) - category identifier
    + categoryName: `Super Category` (string) - category title
    + childCategory (optional, array[Category]) - array of child categories
```

And I get the notice saying: `Base type 'Category' circularly referencing itself.`

**Comment by pksunkara** [comment]
Hey, The API Blueprint does not support self-references in MSON. At least for now.

**Comment by wersoo** [comment]
Hey! Thank you for the answer.

**Comment by Kratos-SA** [comment]
+1

**Comment by zdne** [comment]
We are exploring the possibility of allowing circular references – the use of incomplete name type in value definition. Will keep you updated.

**Comment by pksunkara** [comment]
This is now working using the latest drafter prerelease 2.3.0-pre.1
