### ISSUE TITLE
Links with single quotes don't work properly

### ISSUE THREAD

**Issue by tfedor** [apiaryio/api-blueprint#221]
URLs don't work when contain single quote/apostrophe.

Headers like this:
`# Do's and don'ts`
will render properly but they will generate link like this:
http://docs.itad.apiary.io/introduction/do&#x27;s-and-don&#x27;ts

I guess the issue is with hash sign. When clicked, user is sent to the top of the page.

Similarly, when actions contain single quotes, the action isn't opened when clicked.

**Comment by XVincentX** [comment]
Hey,
I have been able to reproduce the issue and it is now internally tracked in Apiary.
I'll get back to you when it will be solved.

Thanks for the report!

**Comment by honzajavorek** [comment]
[Apiary](http://apiary.io) internal tracking ticket – [Permalinks with quotes do not work properly](https://trello.com/c/Rd32GAPa/436-permalinks-with-quotes-do-not-work-properly)

**Comment by kylef** [comment]
I'm sorry that no one got back to you sooner. I've just tested this particular issue and it appears to work now.

Try the following link: https://itad.docs.apiary.io/introduction/do's-and-don'ts
