### ISSUE TITLE
Create Request/Response Body from Attributes

### ISSUE THREAD

**Issue by MichaelHirn** [apiaryio/api-blueprint#225]
I think MSON is great and powerful. At the same time I think that it is somewhat hard to figure out, what of the four Sections for `request`, `response` one should use to keep the doc human and machine understandable and DRY.

`Schema` gets already generated if `Attributes` is specified but no specific `Schema`, so why not extend this to `Body` as well? Attributes with MSON should already be feature-complete for generating the `Body` if none is specified. MSON allows for example values, which could be used to generate a complete `Body`.

Example:

```
## Item (object)

- name: `ItemName` (string, required)
- value: `6` (number)

## Example (object)

- data: (array[Item], required)
- label: `big` (string)
```

this could generate a `Body` something like this, right out of the box

```
{
  data: [
    {
       name: "ItemName",
       value: 6
    }
  ],
  label: "big"
}
```

 I think a Body example is needed for easier understanding, how payload/responses actually look like - but I think with MSON and Attributes there is no real need to specify them oneself.

**Comment by pksunkara** [comment]
Hey @MichaelHirn. `Attributes` will be used to generate the JSON body if no `Body` is specified and a content-type of `application/json` is given.

Do you have an example blueprint where it is not happening?

**Comment by MichaelHirn** [comment]
@pksunkara Thanks for your fast response. Great to see, that this is already implemented - and works like expected. I just did not catch any hints in the Specification or elsewhere, that this already works. Thanks for sharing.

**Comment by zdne** [comment]
Thanks for your input @MichaelHirn! The fact you haven't discovered it is already a good (bad) signal that we need to improve the accessibility of it, will think what we can do here. Cheers!
