### ISSUE TITLE
Null default value for attribute

### ISSUE THREAD

**Issue by AlexKorovyansky** [apiaryio/api-blueprint#227]
How to define string attribute with null as default value?

I'm trying:
```
+ Attributes
   + prev: null (string) - Prev page url 
```

But apiary interprets it as "null", that's not null.

**Comment by zdne** [comment]
Please see (and feel free to chime in) to the discussion here https://github.com/apiaryio/mson/issues/26

**Comment by HansHauge** [comment]
That other conversation thread is very long. At the end they decided to allow `(string, nullable)` if a string might be null for example.
