### ISSUE TITLE
HOST as a reusable variable

### ISSUE THREAD

**Issue by AlexKorovyansky** [apiaryio/api-blueprint#228]
Let:
```
HOST: http://api.site.com
```

I'd like to reuse HOST definition along a documentation, in order to construct absolute URLs where it's reasonable. Something like:

```
+ Attributes
   + next: $HOST/objects?offset=10&limit=10 (string) - Next page url 
```

Is it possible in some way?

**Comment by zdne** [comment]
> Is it possible in some way?

Unfortunately not. 

There may be a revisit to the `HOST` metadata as discussed here https://github.com/apiaryio/api-blueprint/issues/122 but it weren't really counting with reusing its value anywhere in the document. Please feel to expand #122 

Second thought: Maybe it would be a good idea to consider some sort of URL -relation functionality for composing various URLs for cases like this and HTTP link headers...

**Comment by pksunkara** [comment]
@zdne I assume this issue is closed because of relation functionality, right?
