### ISSUE TITLE
Usage of Advanced Actions breaks mock server

### ISSUE THREAD

**Issue by AlexKorovyansky** [apiaryio/api-blueprint#229]
**Steps to reproduce:**

1. Setup API using https://github.com/apiaryio/api-blueprint/blob/master/examples/12.%20Advanced%20Action.md example
2. Try to call Retrieve task method against Mock server in Console

**Expected result:**

* Successful execution of request

**Actual result:**

* Request fails with error "We are sorry, but the API call failed. Please, give it another try." with additional information in Inspector "This API request did not match any documented resource. Your URL or method are probably wrong."

I guess syntax of the example is correct. It looks like usage of Advanced Actions breaks mock server, because it supports only matching for Standard Actions.

We need to have mock server working with Advanced Actions usage. So what's a fix for that?

**Comment by pksunkara** [comment]
Hey @AlexKorovyansky. Thanks for the bug report. We are going to look into it and see why it's happening.

**Comment by XVincentX** [comment]
Hey,
I am happy to announce that we have just deployed a fix for our mockserver, and now your case use should work as expected.
Could you please give it a try and let me know if everything is working properly?

Feel free to reopen the issue if the problem persists.

**Comment by zdne** [comment]
Thanks @XVincentX for the updates!

**Comment by AlexKorovyansky** [comment]
Thanks @XVincentX 

Sample is working now!

But in our real app it's still broken, after short investigation I can say that reason of the problem is usage of HOST with path.

> HOST: http://api.site.com/general/path

(if I change HOST to `http://api.site.com`, it fixes the problem)

Can you support HOST variable with path?
Or how can I add general path to all API methods in other way?

**Comment by pksunkara** [comment]
@AlexKorovyansky We do not support paths in `HOST`. You would have to add the path to every URL in the API Blueprint.

**Comment by AlexKorovyansky** [comment]
Okay. In such case it's just idea for improvement. Thanks!

**Comment by zdne** [comment]
@AlexKorovyansky, I am afraid we did a mistake here. The behavior should be as follows:

1. Path SHOULD be supported in `HOST` 
2. Advanced action SHOULD work in Apiary.io' mock server

However, while implementing the later, we have introduced a regression issue that broke the former. When we have realized we have rollbacked the "advanced actions".

The current situation is: Paths should work in HOST, the advanced actions in mock are not working but should (to be fixed soon)

Sorry for the confusion!

**Comment by AlexKorovyansky** [comment]
Oh, ETA for the fix? Can you do it till Jul 28? Otherwise I will need to
rewrite our API without usage of Advanced actions, because we need to have
working mock server.

**Comment by AlexKorovyansky** [comment]
@zdne ?

**Comment by AlexKorovyansky** [comment]
Can you please reopen this issue if it's not fixed?

**Comment by XVincentX** [comment]
@AlexKorovyansky The issue has been reopened, and we're working hard to make it done as soon as possible

**Comment by AlexKorovyansky** [comment]
Thanks for the update @XVincentX!

**Comment by chance-schultz** [comment]
Is there any news on this ticket. My company has recently adopted apiary.co and are now experiencing the same bug.

**Comment by XVincentX** [comment]
Hey,
I am afraid I do not have any update for now, but I can surely tell you that we're hardly working on it and a solution should come up in the following days.

Please bear with us,
V.

**Comment by XVincentX** [comment]
@AlexKorovyansky 
@chance-schultz 
Hello,
I am happy to announce you that we have finally deployed Advanced Actions support for Apiary, and they should now work correctly.

Could you please give a new try to that and let me know if everything is working correctly?

**Comment by AlexKorovyansky** [comment]
I can confirm now it's working right. Thanks!

**Comment by ayushav12** [comment]
@XVincentX  Getting the error: "This API request did not match any documented resource. Your URL or method are probably wrong."
Is the mock server breaking again when using advanced actions?

**Comment by XVincentX** [comment]
Hey
you should probably provide an example APIB to reproduce the error.
@ayushav12 could you?

**Comment by ayushav12** [comment]
Here's the APIB in which I got the error:

# CourtAvailability API

This API shows the sessions that can be booked in a facility. 

## Data Structures 

### Time (object)

+ hour (number) 
+ minute (number)

### Date (object)

+ day (number)
+ month (number)
+ year (number)

### DateTime (object)

+ day (number)
+ month (number)
+ year (number)
+ hour (number) 
+ minute (number)

## Court Availability [/courts]

### getAllCourtsAvailability [GET /courts/{date}]

This action retrieves all the sessions (color coded) for all the courts at a specific
date(date specified as URI parameter).

+ Parameters
    + date (Date) - Date to book the seesion 
    
+ Request (application/json)
    + Attributes
       - Softbooked_Sessions (DateTime)
       - Booked_Sessions (DateTime)
       - Available_Sessions (DateTime)

+ Response 200 (application/json)
    + Attributes
       - User_id (number) - Id of the user
       - session_from (Time) - Start time for each available session
       - session_for (Time) - duration of each available session
       - retrieve_upto (Date) - retireves availability of courts 
       upto the date specified
      
       

### getCourtAvailability  [GET /courts/{id}/{date}]

This action retrieves all the sessions (color coded) for a specified court at a specified
date(court_id and date specified as URI parameters).

+ Parameters
    + id (number) - Id of the court.
    + date (Date) - Date to book the session.
    
+ Request (application/json)
    + Attributes
       - Softbooked_Sessions (DateTime)
       - Booked_Sessions (DateTime)
       - Available_Sessions (DateTime)
      
+ Response 201 (application/json)
    + Attributes
       - User_id (number) - Id of the user.
       - session_to (Time) - Start time for available sessions
       - session_from (Time) - End time for available sessions
       - retrieve_upto (Date) - retireves availability of courts 
       upto the date specified

**Comment by pksunkara** [comment]
Can you try changing GET to POST in the both the actions?

**Comment by ayushav12** [comment]
I have to define the actions using GET method as per the design of the API. Can you suggest an alternative please??

**Comment by pksunkara** [comment]
`GET` actions shouldn't have request bodies.
