### ISSUE TITLE
Apiary Blueprint Docs: Unable to disable/hide schema

### ISSUE THREAD

**Issue by foxx** [apiaryio/api-blueprint#232]
If you add attributes to a request, Apiary docs will automatically generate and output a schema. This is not always desired, and although you can replace schema with `{}`, there is no way to remove it completely. It would be nice to have the ability to optionally disable schema from being shown (perhaps if `schema` is empty? Currently if it's empty, it just outputs the generated schema from attributes)

**Comment by pksunkara** [comment]
Thanks for the suggestion. I was thinking the same and will message my colleagues about this.

**Comment by jeremytm** [comment]
:+1:

**Comment by pascalbaljet** [comment]
+1

**Comment by bjorkblom** [comment]
+1

**Comment by svvitale** [comment]
+1

**Comment by mapb** [comment]
+1

**Comment by dzemidzv** [comment]
+1

**Comment by eon** [comment]
+1

**Comment by mcanaves** [comment]
+1

**Comment by szimin18** [comment]
+1

**Comment by jeremytm** [comment]
@pksunkara any idea when this will be done? It seems like something that should be fixed before disabling legacy. It's the only issue that still remains for us before I'd be happy calling our documentation 1.0

**Comment by paraskakis** [comment]
Hi Jeremy,

It's something we have in the backlog, for the short term (i.e a few weeks). Unfortunately I can't promise you an exact date, but we'll announce it here.
Is it very urgent for you?

Thanks,

Emmanuel

**Comment by jeremytm** [comment]
It won't stop someone from using our API, but it does make things bloated and more complicated than it needs to be for new users. Thanks for the update.

**Comment by gigafied** [comment]
If we can get this in by Nov 15th that would be swell :)

**Comment by BernieN** [comment]
+1

**Comment by paraskakis** [comment]
The plan is to collapse the schema in the documentation so it's not visible by default. You would be able to expand it to see it. We thought this is more flexible than having say a switch in Settings that turns it off completely. This is coming up on our next sprint so four weeks is the ETA.

**Comment by jeremytm** [comment]
Thanks @paraskakis, sounds good :)

If it could also appear somewhere other than in-between the attributes and response-body sections that would be ideal. It's just that where it appears now, it can be confusing to people who have no use for schemas.

**Comment by BernieN** [comment]
+1 for jeremytm's proposal

**Comment by Clar64** [comment]
I had a look at our docs now and this seems completed. Thanks!!

**Comment by pksunkara** [comment]
Thanks guys! :smile:

**Comment by jeremytm** [comment]
Yep, the implementation is perfect! Though now we have lost the attributes section :'(

**Comment by Clar64** [comment]
@jeremytm My attributes still show?

**Comment by jeremytm** [comment]
I've done some investigating. The new bug seems to only be affecting Attributes by way of Data Structures.

See the [official Apiary Data Structures example](https://github.com/apiaryio/api-blueprint/blob/master/examples/10.%20Data%20Structures.md). 

For example, under the "Create a coupon" interactive area, we should see the `Coupon Base` data structure attributes listed as general attributes, and we should see the `Coupons` data structure attributes listed under the response. We no longer see either of these lists.

All of our attributes sections rely on Data Structures. Are these examples not being tested before each release?

**Comment by zdne** [comment]
Hey @jeremytm, thanks for pointing the regression issue out. I believe it has been just fixed and the Data Structures are now being rendered as before.

**Comment by zdne** [comment]
For the record: At Apiary, we have added the button to show and hide JSON schema in the rendered documentation. The schemas are hidden by default. Example: 

![screen shot 2015-11-09 at 2 38 34 pm](https://cloud.githubusercontent.com/assets/613617/11035003/ceac7fe8-86ef-11e5-931e-eaeaec3b4d46.png)

**Comment by BernieN** [comment]
Like it. Thanks for that!
