### ISSUE TITLE
Ability to reference repeated data

### ISSUE THREAD

**Issue by foxx** [apiaryio/api-blueprint#236]
Imagine the following scenario;

```markdown
## Say hello [POST /say/hello]

Say hello to someone

+ Request (application/json)

    + Attributes
        + message (boolean) - Your hello message

    + Body
    
            {"message": "Japie, start the nederdraad!"}

    + Schema

            {}

+ Response 200 (application/json)
    + Body

            {}
    + Schema

            {}

+ Response 400 (application/json)
    + Body

            {"errors": [
                {"message": "some error", "code": 1},
                {"message": "some error", "code": 1}
            ]}
    + Schema

            {}
```

Lets assume that 4xx response will always contain the same data structure for all API endpoints. Rather than having to repeat this data structure definition multiple times, it would be useful to define it once in the document and then reference to it. Models do not work for this, because they require that you define a path, which doesn't really make much sense (as a data structure is independent of its resource path, right?).

I've had a read through some other issues which feel related, including #29, #25, #9 and #19, but none of them seem to provide any solution or firm outcome.

Could someone please clarify the correct way of achieving the above goal?

**Comment by pksunkara** [comment]
I think you are looking for [MSON](https://github.com/apiaryio/mson) with which you can do the above.

**Comment by foxx** [comment]
MSON could potentially help, but I don't want to use MSON in this particular situation :)

**Comment by pksunkara** [comment]
I don't know why you do not want to use MSON, but MSON was designed exactly with this use case in mind.

**Comment by kylef** [comment]
@foxx Just to be clear, @pksunkara is proposing you do something like follows. Where you are defining reusable components you can use in multiple different resources/actions.

```apib
## Say hello [POST /say/hello]
+ Response 400 (application/json)
    + Attributes(errors)

## Data Structures
### Errors
+ errors (array[Error])

### Error
+ message: some error
+ code: 1 (number)
```

Which would get expanded into the following JSON example in Apiary:

![screen shot 2015-07-22 at 14 49 21](https://cloud.githubusercontent.com/assets/44164/8825641/dd7b35de-3080-11e5-9672-33c240bc8bc0.png)

**Comment by foxx** [comment]
Oh interesting, actually yes you're quite right this would solve the issue.

I couldn't see any mentioning of this in the examples or documentation, at least not clearly, did I miss something?

**Comment by pksunkara** [comment]
There are a few examples in the example folder such as, [Attributes](https://github.com/apiaryio/api-blueprint/blob/master/examples/08.%20Attributes.md), [Advanced Attributes](https://github.com/apiaryio/api-blueprint/blob/master/examples/09.%20Advanced%20Attributes.md) and [Data Structures](https://github.com/apiaryio/api-blueprint/blob/master/examples/10.%20Data%20Structures.md)

**Comment by foxx** [comment]
Thanks for the quick reply and additional info, appreciated
