### ISSUE TITLE
Underscores in JSON payload break Sublime Text & GitHub syntax highlighting

### ISSUE THREAD

**Issue by czechboy0** [apiaryio/api-blueprint#241]
It seems like keys that contain an underscore break highlighting for the whole `apib` file, see https://github.com/czechboy0/XcodeServer-API-Docs/blob/master/apiary.apib#L136. This is different than the MSON underscore issue, because there underscores are reserved characters, whereas in JSON they are allowed.

Would be great if this could get fixed in both parsers (Sublime Text's and GitHub's).

**Comment by danielgtaylor** [comment]
Thanks for reporting this. I believe that adding support for the `+ Model` section should help fix this by preventing the markdown rules from taking over there.

**Comment by kylef** [comment]
@danielgtaylor Regardless of native support for `+ Model` section, this should be a code block in plain markdown (four spaces within a list item) so it should be rendered as a code block regardless of the list item content (`Model` as a string).

**Note**: *I believe there are plans to deprecate/remove model. I wouldn't suggest adding native support for it within the lexers https://github.com/refractproject/rfcs/pull/1#discussion_r33555698*

**Comment by czechboy0** [comment]
@kylef Does that mean there would be no way to copy/paste example JSON responses into API Blueprint? I'd see that as a regression if not provided with an automatic JSON/XML/... -> MSON converter.

**Comment by kylef** [comment]
@czechboy0 You would still be able to copy-paste example code into API Blueprint examples.

I've closed this issue to move it to the sublime plugin (which is how GitHub also does the rendering) https://github.com/apiaryio/api-blueprint-sublime-plugin/issues/29

As a workaround, you could use fenced code-blocks as shown in the following example until this issue has been resolved.

```apib
+ Model (application/json)

     ```
    {
      "_id": "963bc95f1c1a56f69f3392b4aa03302f"
    }
     ```
```
