### ISSUE TITLE
POST Data Parameters

### ISSUE THREAD

**Issue by kennydude** [apiaryio/api-blueprint#242]
Hi, I was wondering if there's a possibility to add a section similar to `+ Parameters` but is designed for POST data? Something like `+ Body` would be fine.

Currently I use Parameters but I'm not happy about dredd throwing warnings about it and it feels messy. Also the Request section on Apiary gives me just a text area to enter the POST body which isn't as nice as other API consoles I've used.

Currently on Apiary I'm only able to get this for the console:

![screenshot from 2015-08-05 10 46 07](https://cloud.githubusercontent.com/assets/198294/9082938/3fc2b544-3b5f-11e5-953f-f4d72d5643ca.png)

Whereas Django Rest Framework's browsable API is able to give me a form which looks like so. I think having the form just makes it look a lot nicer and clearer what each attribute is meant to do.

![screenshot from 2015-08-05 10 47 37](https://cloud.githubusercontent.com/assets/198294/9082961/6b606eda-3b5f-11e5-8df9-7a89ff0c05e7.png)

**Comment by pksunkara** [comment]
@kennydude Have you looked at [Attributes](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section)? Here is an [example](https://github.com/apiaryio/api-blueprint/blob/master/examples/08.%20Attributes.md).

**Comment by kennydude** [comment]
Thanks, I hadn't seen that. The example doesn't demonstrate it in the same usage which is what threw me off a bit
