### ISSUE TITLE
Repetitive Request Titles

### ISSUE THREAD

**Issue by jeremytm** [apiaryio/api-blueprint#244]
Has something changed in the last day or so?

Requests which used to show nice and tidily like this:
![screen-shot-2015-08-05-at-1 21 35-pm](https://cloud.githubusercontent.com/assets/6539834/9127493/d3465eea-3d0f-11e5-824a-1688200b74fa.png)

Now show like this:
<img width="716" alt="screenshot 2015-08-07 14 22 56" src="https://cloud.githubusercontent.com/assets/6539834/9127496/de44c6ec-3d0f-11e5-9485-dad3d340c8c7.png">

Obviously this repetition is unnecessary.

Here's the simplified markdown:

```
## Group Manager

### Get a manager  [GET /managers/{id}]

+ Parameters
    + id (number, `1`)

+ Response 200 (application/vnd.api+json)

        {
        }

### Get a manager including clubs [GET /managers/{id}?include={relationships}]

+ Parameters
    + id (number, `2`)
    + relationships (comma separated list, `allClubs,currentClub`)

+ Response 200 (application/vnd.api+json)

        {
        }
        
        
### Get managers paginated [GET /managers]

+ Response 200 (application/vnd.api+json)

        {
        }
```

**Comment by miiila** [comment]
Hi @jeremytm,

there were no changes about rendering documentation in past few days. Have you done any changes in your blueprint recently so it could affect rendering?

Thank you
Mila

**Comment by jeremytm** [comment]
Ok, I finally went through your examples here:
https://github.com/apiaryio/api-blueprint/tree/master/examples

I wish I'd done this ages ago! It would have saved me so much time. There's some awesome stuff there I didn't know existed. Anyway, I found a couple of issues which I think are related.

In your [Advanced Actions](https://github.com/apiaryio/api-blueprint/blob/master/examples/12.%20Advanced%20Action.md) example, I see this:
![screenshot 2015-08-08 12 43 04](https://cloud.githubusercontent.com/assets/6539834/9148347/01008852-3dcd-11e5-8dd1-563e1839ea3c.png)
Note how the tasks label is used twice in both the menu, and the body. The main title is **Default** as well which isn't actually written as a title in the blueprint. I think the title should be Tasks, and then those subtitles shouldn't be there at all.

In your [Named Endpoints](https://github.com/apiaryio/api-blueprint/blob/master/examples/13.%20Named%20Endpoints.md) example, I see this:
![screenshot 2015-08-08 12 42 39](https://cloud.githubusercontent.com/assets/6539834/9148387/08111dc2-3dce-11e5-9083-0b37c2a34df4.png)
I'm not sure if this is intentional, but the titles are repetitive there, whereas they only appear once in the blueprint.

**Comment by pksunkara** [comment]
@XVincentX Can you look into this bug?

**Comment by smizell** [comment]
@pksunkara @XVincentX I've created an internal issue for tracking and have been able to duplicate this issue.

It seems to be related to using the syntax for `Action Name [POST /resource]`. If this occurs within a resource, it is treated as a different resource in the documentation.

**Comment by pksunkara** [comment]
It should be treated as the same resource instead of a different one.

**Comment by honzajavorek** [comment]
[Apiary](http://apiary.io) internal tracking ticket – [Bug: Duplicate Resources in Documentation](https://trello.com/c/cUMj0lu5/490-bug-duplicate-resources-in-documentation)

**Comment by pksunkara** [comment]
@jeremytm 

This has been fixed but you might need to make a small change to your initial blueprint if you want it to be displayed like before.

Please add the following line after `Group Manager`.

```
## Managers [/managers]
```

**Comment by pksunkara** [comment]
Regarding the examples:

The `Named Actions` example's rendering is intentional. While the `Advanced Actions` example's rendering has now been fixed.

Thanks.
