### ISSUE TITLE
Side-menu links go to wrong place

### ISSUE THREAD

**Issue by jeremytm** [apiaryio/api-blueprint#245]
If there are two sub-titles with the same name, clicking any of them will take you to the last one.

For example, here is a basic rendered blueprint showing a link I then click.

![screenshot 2015-08-08 12 55 03](https://cloud.githubusercontent.com/assets/6539834/9148423/344f4822-3dcf-11e5-84ef-b4fd810ce618.png)

If I click the menu item marked **above**, I am then take to where shown **below** which is unexpected.

![screenshot 2015-08-08 12 55 12](https://cloud.githubusercontent.com/assets/6539834/9148433/5be58324-3dcf-11e5-8210-ab96abd32be7.png)

Only a minor issue since it's easily worked around by making sure all sub-titles are unique.

But then that means we can't produce elegant documentation with consistent 'Example' titles in each top level section.

Here's the blueprint:

``` markdown
FORMAT: 1A

# Bug

## Intro 1

### Something fun 1

Hello

### Example

Example

## Intro 2

### Something fun 2

Hello

### Example

Example
```

**Comment by honzajavorek** [comment]
Hello, I was able to reproduce this. Thanks for reporting! :balloon: 

[Apiary](http://apiary.io) internal tracking ticket – [Same sub-header names confuse anchoring within documentation, links lead to still the same target](https://trello.com/c/tpfTiUqR/1054-same-sub-header-names-confuse-anchoring-within-documentation-links-lead-to-still-the-same-target)

**Comment by zdne** [comment]
@honzajavorek any update on this?

**Comment by kylef** [comment]
I believe this has been fixed, if you're still hitting problems please let us know.
