### ISSUE TITLE
Sample Tesla API blueprint on the website does not produce the same docs using Apiary.io editor

### ISSUE THREAD

**Issue by darkaeon10** [apiaryio/api-blueprint#246]
I found the sample Tesla API here: http://docs.timdorr.apiary.io/

I was hoping to do something similar to the Vehicles > State and Settings section. 

![correct](https://cloud.githubusercontent.com/assets/1049495/9191531/f8480dce-4034-11e5-9aea-9d2e293bae2f.png)

As you can see, 'Mobile Access' and 'Charge State' are different actions grouped under 'State and Settings'. Furthermore, these two different actions have different URLs. That is,

'Mobile Access' : 
GET https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/mobile_enabled
'Charge State' : 
GET https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/data_request/charge_state

But despite having different URLs, they are still grouped together under 'State and Settings', presumably because they had a common path in their URLs (/api/1/vehicles/{vehicle_id}). And it seems to be the case, because looking at the blueprint, I found that the 'State and Settings' group had the following url declared:
 ## State and Settings [/api/1/vehicles/{vehicle_id}]

Now, I wanted to achieve the same effect but to no avail. I tried copy-pasting the whole Tesla Motors API blueprint (found here: https://jsapi.apiary.io/apis/timdorr.apib) onto the editor in Apiary.io, but it instead created a lot of different 'State and Settings' tabs, instead of all the actions being grouped under one tab. Screenshot is provided below.

![screenshot from 2015-08-10 16 24 23](https://cloud.githubusercontent.com/assets/1049495/9163454/8ba320d6-3f7c-11e5-95cd-15ee3d79a564.png)

Any help would be greatly appreciated. Thank you.

**Comment by zdne** [comment]
@honzajavorek isn't this duplicate to #244 and / or #245

**Comment by pksunkara** [comment]
Yes, I think this is a duplicate to #244

**Comment by honzajavorek** [comment]
Sorry, I missed this conversation. It looks like the same problem indeed, so you're right, it's duplicate.

**Comment by zdne** [comment]
@darkaeon10 please track this issue in #244

**Comment by darkaeon10** [comment]
@zdne alright, thanks!

**Comment by zdne** [comment]
No worries!
