### ISSUE TITLE
Escape hyphen in attribute example value

### ISSUE THREAD

**Issue by darkaeon10** [apiaryio/api-blueprint#248]
Hi, I'm editing a blueprint on Apiary.io. 
I've been trying to add an example value to a response attribute. See snippet below.

+ Response 201 (application/json)
    + Attributes
        + message: Hello-World (string) - description of the message attribute

The question is, how can I escape the hyphen in Hello-World? It seems that anything after the first hyphen becomes part of the attribute description. I've tried escaping with \, and surrounding the hyphen with `. Both don't seem to work. 

Any help would be greatly appreciated. Thanks!

**Comment by pksunkara** [comment]
You can use backticks to escape MSON reserved characters.

```apib
+ message: `Hello-World` (string) - description
```

**Comment by darkaeon10** [comment]
Thanks and sorry for the trouble! I just checked and using backticks solved the problem. The live preview just wasn't updating properly.

**Comment by bennettellis** [comment]
I have an parameter called
```template_type```
type is apparently a keyword
I try using the backtics around the full parameter name and just the word ```type``` but in both cases I get the same error, "Ignoring unrecognized block".  If I leave it as template_type, it semantically clears the checks, but my parameter is ignored and not presented in the API doc in the example or the console. What am I doing wrong?

**Comment by bennettellis** [comment]
never mind.  Figured it out -- URL encoded both param in the URI and in the parameter list and it works fine.
