### ISSUE TITLE
Override attribute value of Data Structure 

### ISSUE THREAD

**Issue by darkaeon10** [apiaryio/api-blueprint#249]
Say I have this Data Structure:

# Data Structures

## Response (object)

+ status: 0 (number, required) - status code
+ message: Request Successful! (string, required) - description of the status code
+ data (object, required) - contains relevant information regarding the request

Then in a specific action, I want to set the example response to this object, like this:

+ Response 201 (application/json)
    + Attributes (Response)

However, I want to override the status and message attribute values, and set the data attribute to some value. Is this possible?

**Comment by pksunkara** [comment]
You can do this:

```apib
+ Response 201 (application/json)
    + Attributes (Response)
        + message: Request unsuccessful.
```

PS: There's a bug effecting the JSON rendering when attributes are overwritten, but we have a fix on the way.

Please read the [MSON Specification](https://github.com/apiaryio/mson) and [API Blueprint Specification](https://github.com/apiaryio/api-blueprint) more clearly. Thanks.

**Comment by darkaeon10** [comment]
Ah yes, I've tried that but the JSON being rendered on Apiary.io doesn't seem to be right. Glad to know you've got a fix on the way. Thanks!

**Comment by buildjosh** [comment]
Is there any update on this?

**Comment by pksunkara** [comment]
@buildjosh Yes, the bug when the attributes are overwritten is fixed in the parser's latest release.
