### ISSUE TITLE
Message-body Attributes Description

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint#25]
Documentation of message-body attributes. Similar to URI parameters.

Also if possible it should be clearly differentiated between the URI parameters description and Body Parameters description. Current state with the `parameters` section of a resource (action) might lead to confusion what parameters are discussed.

**Comment by jrep** [comment]
The branch of snowcrash named here, "pksunkara/attributes," does not exist. There is a pksunkara/mson-sourcemap, should I use that?


> On Dec 12, 2014, at 2:05 AM, Z <notifications@github.com> wrote:
> 
> Alpha testing API Blueprint Attributes
> 
> API Blueprint Attributes is a major update to the API Blueprint <https://github.com/apiaryio/api-blueprint/tree/zdne/attributes-description> introducing description of data structures using the MSON <https://github.com/apiaryio/mson> syntax.
> 
> NOTE: The Attributes syntax is NOT implemented in the Apiary application just yet – at the moment it can be tested ONLY from the command line and / or Sublime Text 3.
> 
> What is Needed
> 
> During this phase of testing we are looking mainly at:
> 
> API Blueprint Attributes syntax
> MSON syntax
> The clarity of MSON specification <https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md>
> Implementation of the syntax in the parser
> The clarity of parser warning & error messages
> Getting Started
> 
> At this stage the Attributes are implemented in the API Blueprint parser - Snow Crash <https://github.com/apiaryio/snowcrash> and its Node.js binding – Protagonist <https://github.com/apiaryio/protagonist>. Currently there no tools utilizing the API Blueprint Attributes.
> 
> Therefore, the testing is limited to writing and validating (parsing) blueprints with the Attributes sections <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/API%20Blueprint%20Specification.md#def-attributes-section> in it. The validation can be performed either from the command-line or using the API Blueprint Sublime Text plug-in <https://github.com/apiaryio/api-blueprint-sublime-plugin>.
> 
> Writing a Blueprint
> 
> The best way to test the syntax and implementation is to write an actual blueprint using the syntax.
> 
> To learn more about the syntax check following examples:
> 
> Attributes example <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/examples/08.%20Attributes.md>
> Advanced Attributes example <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/examples/09.%20Advanced%20Attributes.md>
> Data Structures example <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/examples/10.%20Data%20Structures.md>
> and respective sections in API Blueprint specification:
> 
> Attributes section <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/API%20Blueprint%20Specification.md#def-attributes-section>
> Resource section <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/API%20Blueprint%20Specification.md#def-resource-section>
> Action section <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/API%20Blueprint%20Specification.md#def-action-section>
> Payload section <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/API%20Blueprint%20Specification.md#def-payload-section>
> Data Structures section <https://github.com/apiaryio/api-blueprint/blob/zdne/attributes-description/API%20Blueprint%20Specification.md#def-data-structures>
> The new Attributes syntax is introduced in this [Pull Request][Attributes PR].
> 
> To learn more about the MSON syntax (the actual syntax used inside the Attributes section) check the MSON specification <https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md>.
> 
> Validating Blueprint from CLI
> 
> When it comes to validating a blueprint with Attributes section from CLI you have two options:
> 
> Install & use Snow Crash CLI tool
> Install & use Protagonist (requires Node.js)
> Snow Crash CLI tool
> 
> To install Snow Crash CLI tool with Attributes support in it:
> 
> $ git clone --recursive git://github.com/apiaryio/snowcrash.git
> $ cd snowcrash
> $ git checkout pksunkara/attributes
> $ ./configure
> $ make install
> To validate a blueprint run:
> 
> $ snowcrash --validate path/to/blueprint
> Protagonist CLI tool
> 
> With a Node.js (v0.10) installed, run:
> 
> $ npm install protagonist-experimental
> $ cd node_modules/protagonist-experimental
> $ npm install
> To validate a blueprint run:
> 
> $ node node_modules/protagonist-experimental/tools/protagonist.js path/to/blueprint
> Validating Blueprint using Sublime Text 3
> 
> For this step you will still need to install Snow Crash CLI tool as described above. Once installed, install the Sublime Linter 3 package and API Blueprint package preferably using the Package Control.
> 
> For manual installation refer to the API Blueprint Sublime Text plug-in <https://github.com/apiaryio/api-blueprint-sublime-plugin> README.
> 
> Once installed, set file syntax to API Blueprint, the warning, if any should occur in the ST3 status bar:
> 
>  <https://cloud.githubusercontent.com/assets/613617/5409765/28e71da4-81ee-11e4-8f03-431c567c342b.png>
> Submitting the Feedback
> 
> The feedback can be split into following categories:
> 
> Parser implementation, warning & errors
> 
> Add a comment to the Snow Crash Attributes PR <https://github.com/apiaryio/snowcrash/pull/262>.
> 
> API Blueprint Attributes syntax & spec issues
> 
> Add a comment to the API Blueprint Attributes PR <https://github.com/apiaryio/api-blueprint/pull/135>.
> 
> MSON syntax & spec issues
> 
> Submit as a new issue <https://github.com/apiaryio/mson/issues> in the MSON <https://github.com/apiaryio/mson> repository.
> 
> Unsure? Just add a comment here.
> 
> Questions?
> 
> Just add them here or email me directly at z@apiary.io <mailto:z@apiary.io>.
> 
> Thank you!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/apiaryio/api-blueprint/issues/25#issuecomment-66753722>.
> 

--
Jack Repenning
Jack@netgate.net

**Comment by andrewtweber** [comment]
Any ETA on when this will be available for all Apiary users?

**Comment by zdne** [comment]
@andrewtweber current estimates are looking at the end of February

**Comment by marcus-maws** [comment]
Is the ETA for implementation on Apiary still the end of Feb?

**Comment by catesandrew** [comment]
@zdne Currently updating API docs with the experimental branch. By the way, awesome work!! When would I want to use `Properties` over `Attributes`? I see both being used in @jrep's gist he posted.

**Comment by robbinjanssen** [comment]
@zdne any update you want to share on this? :)

**Comment by zdne** [comment]
@robbinjanssen @marcus-maws well, I can but it will be more promises :) I hope to deliver something instead.

**Comment by zdne** [comment]
We are rolling out this huge release. Please stay tuned. I will update this thread once the attributes are available in Apiary.

**Comment by Quagh** [comment]
@zdne Just for info, will it be a matter of hours, days, weeks, … ? As I'm currently writing documentation with attributes and would like to know if I should postpone it to avoid writing the attributes section twice :)

**Comment by mishak87** [comment]
There should have been probably newsletter for this feature :smile:.

**Comment by zdne** [comment]
@Quagh for parser & tools we are looking at hours, for Apiary we are looking at days (=this week), (@Baggz correct me if I am wrong :package: )

**Comment by zdne** [comment]
@mishak87 Good point! For now we are definitely going to announce it at https://twitter.com/apiblueprint and here. There will be a blog post at Apiary.io once the it is fully supported – news letter is something we are considering as well.

**Comment by zdne** [comment]
Note the initial implementation at Apiary.io will render only top-level attributes. By this I mean Apiary.io rendered documentation. The syntax and JSON and JSON Schema generation will work from the start.

**Comment by DataGreed** [comment]
Will tools like aglio work out of the box or should they be updated to
support this?

sent from a small handheld device with autocorrection
30 марта 2015 г. 19:42 пользователь "Z" <notifications@github.com> написал:

**Comment by LabLayers** [comment]
Finally! :+1:

**Comment by zdne** [comment]
@DataGreed 


Unfortunately not. Tools like Aglio needs to be updated to render the attributes. Once updated to the latest parser you will be able to use the syntax but you won't see it rendered until the tool is updated.

**Comment by thomask** [comment]
Hi, any updates for Apiary yet? Thanks!

**Comment by zdne** [comment]
@thomask We have ran into unexpected issues while deploying on production. We are currently working around the clock to fix these. I will keep this thread updated. Sorry about this.

**Comment by thomask** [comment]
No worries of course! Looking forward to the release

**Comment by robbinjanssen** [comment]
Using the latest format for our own documentation and it works great! Thanks!

**Comment by zdne** [comment]
Update: Apiary now supports rendering of JSON and JSON Schema as well as simplified rendering of attributes:

![screen shot 2015-04-20 at 5 05 38 pm](https://cloud.githubusercontent.com/assets/613617/7243222/8f4752a2-e77f-11e4-9c48-ba67c16698d7.png)

You can find some examples to get started here:

- https://github.com/apiaryio/api-blueprint/blob/master/examples/08.%20Attributes.md
- https://github.com/apiaryio/api-blueprint/blob/master/examples/09.%20Advanced%20Attributes.md
- https://github.com/apiaryio/api-blueprint/blob/master/examples/10.%20Data%20Structures.md

**Please let us know how you like it!** 

Either on Twitter, here (feel free to open a new issue) or at Gitter. 

[![Join the chat at https://gitter.im/apiaryio/api-blueprint](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/apiaryio/api-blueprint?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Thank you all for your patience waiting for this – so much needed – feature!

Support for rendering of every feature (nested objects, additional sample values, data structures  & more ...) is in the making.

**Comment by jrep** [comment]
Doesn't seem to work. Attached apib does not render the Attributes info anywhere.

Am I being too eager about your "now"? Did you really mean "as of the next build" or something?

--
Jack Repenning
Jack@netgate.net

**Comment by zdne** [comment]
@jrep it should be really now as in right know – I can't see any attachment – can you please paste in in the body of the email or directly into GitHub?

**Comment by zdne** [comment]
This is just a doodle blueprint but it works – http://docs.attributes2.apiary.io

**Comment by pzurek** [comment]
So happy to see this done. I was waiting for this to start documenting our new API. Now there is nothing holding me back. Starting first thing tomorrow.

Just a little nitpick. It feels like the `required` parameter doesn't make much sense on a response.
At the same time, if someone uses the same object for the request and response it would make sense to mark certain attributes as `read-only` (or `response-only`) to make clear that they cannot be posted back.

**Comment by zdne** [comment]
@pzurek thanks for your feedback!

The `required` parameter is related to a property respectively to the data structure, not necessarily in the context of request / responses. 

So if you se a property that is `required` it should be interpreted as **"this property MUST occur in the data structure"** be it response or request. In the context of a response this should be interpreted as **"this property is always present in the response"**.

When it comes to `read-only` – this is why we have introduced `fixed` (think of it as **"const"**) parameter. A property marked as `fixed` is essentially immutable and `required` therefore it should be interpreted as **"property that is always present and its value cannot be changed"**

Let me know whether this makes sense.

**Comment by jrep** [comment]
On Apr 20, 2015, at 8:08 PM, Z <notifications@github.com> wrote:
> 
> This is just a doodle blueprint but it works – http://docs.attributes2.apiary.io <http://docs.attributes2.apiary.io/>Oh, I see it. I was expecting the attributes table to render in the middle, "human" panel, but I see it now over in the right-hand "machine" panel.

My bad.

--
Jack Repenning
Jack@netgate.net

**Comment by pzurek** [comment]
@zdne I'm not entirely convinced. I subscribe to the view that there are no "optional" attributes on the object in the response. Something may be null or not but if it's a field on an object it should always be included in the payload. Plus I would like my docs to be as clear as possible at first sight with no additional explanation required. But I think I will simply put **read-only** annotations in descriptions to get around this.

**Comment by grojguy** [comment]
I hate to complain because there's some neat stuff here, but I'm super disappointed as it appears the new Attributes do not render in the previous (better IMHO) document format?  If so, that's a major bummer!  I fail to understand why, as it would be pretty much the same as the way URI Parameters currently render, right?   Am I back to manually creating markdown tables for Attributes?

Also it would seem that the URI parameters `<description>` does not render in either the old *or* new Apiary document format??    Check it out in the Advanced Attributes example.  (`<additional description>` *does* render.)
<pre><code>+ &lt;parameter name&gt;: `&lt;example value&gt;` (&lt;type&gt; | enum[&lt;type&gt;], required | optional) - &lt;description&gt;

    &lt;additional description&gt;

</code></pre>

Am I the only one bummed by this?  Is the previous documentation format being deprecated?  The new format is a big departure.  I like the idea, but it's nowhere near as concise as the old, too 'big' and spread-out, not screen-space-efficient, and doesn't work for us.

**Comment by zdne** [comment]
Hey @grojguy, I am sorry that you are disappointed with what we do. Please let me clarify few things. The old rendered documentation is at the end of its life, discontinued and will be completely removed soon. I do not think we will add support for rendering the attributes in it. We would really like to hear any feedback on the new rendered documentation  and any reasons why it does not work for you. 

As for the new documentation – the MSON rendering is not complete there just yet. Please follow the https://github.com/apiaryio/api-blueprint/issues/191 for updates on this.

Thanks!

**Comment by kpande** [comment]
Sorry if this is the wrong place for this question, I am trying to model the incoming body of a PUT request to create an account,
```
### Create account [PUT /users]

+ Request (application/json)

        {
            "role": 9,
            "client": 1,
            "username": "newuser",
            "name": "Real Name",
            "email": "newuser@example.com",
            "timezone": "America/Toronto",
            "locale": "en_CA",
            "active": 1
        }

+ Response 200 (application/json)

    + Attributes (object)
        + Include Success
        + data (User, sample) - Newly inserted record is returned upon success
```

Instead of having JSON embedded, is there a way to use Attributes so there may be format-agnostic output and other fancy treatment by API Blueprint tooling?

By the way, I really do love this suite. It makes life better. :+1:

**Comment by pksunkara** [comment]
@kpande Request also allows attributes just as exactly as Response does.

**Comment by thomask** [comment]
Hi, any updates on the progress for attributes with nested objects? Thanks!

**Comment by zdne** [comment]
Hey @thomask, you can track the progress of works on Apiary renderer in #191 .
