### ISSUE TITLE
Usage of data structures in Parameters

### ISSUE THREAD

**Issue by maranomynet** [apiaryio/api-blueprint#250]
(This is not immediately clear from the API docs)

What I'm trying to document is a simple fire-and-forget logging API that defaults to accepting POST with normal URL-encoded form-values in the HTTP body.

It however also allows logging via GET requests with the same parameters tucked on to the URL. (For convenience, and an emergency workaround for certain browser-specific edge-cases.)

This lead me to wonder how to document this without copy-paste repeating the GET Parameters as POST attributes - as I presume URL-encoed form-values sent with POST qualify as Attributes rather than Parameters - no?

What would be the simplest and DRYest way to define this?

**Comment by pksunkara** [comment]
> as I presume URL-encoed form-values sent with POST qualify as Attributes rather than Parameters

Yes, they do.

Unfortunately, you cannot use the Data Structures in Parameters yet. We are still working on adding complete support for Data Structures first.

**Comment by maranomynet** [comment]
Thanks for the clarification.

Most, if not all, of the examples show JSON or YAML payloads - but it would be helpful to also give explicit examples of POST submissions from simple HTML forms. (Or highlight them more clearly if they're there already.)

**Comment by zdne** [comment]
RFC proposal of syntax addressing this issue: https://github.com/apiaryio/api-blueprint-rfcs/pull/3. 

Please track and comment on the RFC.

Thank you!
