### ISSUE TITLE
MSON Sample values

### ISSUE THREAD

**Issue by jamesramsay** [apiaryio/api-blueprint#251]
Is it possible to use samples to render multiple examples in Apiary? (reference: https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#44-sample)

For example, it might be important to demonstrate a number of different and equally valid entity instances to help explain the practical use of the API.

Trying to use Samples, I couldn't get them to render in Apiary.

``` apiblueprint
FORMAT: 1A

# Example

## Item [/item/{id}]

+ Parameters
    - id: 23 (number)

### Retrieve an Item [GET]

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Item)

# Data Structures

## Item (object)

- id (number, required)
- name (string, required)

### Sample

- id: 1
- name: One

### Sample 2

- id: 2
- name: Two
```

None of the samples are used when rendering the example response.

**Comment by zdne** [comment]
@jamesramsay good question. Currently it is not possible. I will leave up to @honzajavorek to reply whether support for rendering multiple samples is planned as early as #191

**Comment by pksunkara** [comment]
@zdne I think this is more related to C++ Boutique and allowing users an option to select a sample for rendering during a specific part of the data structure usage.

**Comment by zdne** [comment]
@pksunkara good point. So we will need to render additional representations and apiary will need to add a way to display them... How is API refract doing with multiple representations rendered for attributes? Feels like we will need to provide a stand alone MSON renderer as well. 

Either way Apiary.io still can display multiple (different) samples in the table..

**Comment by pksunkara** [comment]
Currently, we are just taking the first sample and using it in rendering.

**Comment by honzajavorek** [comment]
Yes, I think currently Boutique takes the first sample and renders it. I can imagine it could be used to render multiple representations based on multiple samples, but I'm not sure about all the consequences. There are more situations like this - e.g. in case of *enum* or *one of*, Boutique always works just with the first option when rendering JSON.

Regarding rendering in Apiary, I have couple of questions.

- Aren't multiple rendered JSON bodies actually just multiple possible requests/responses? In that case, Apiary could render those multiple possible representations simply as alternative requests/responses.
- What about JSON Schema rendering? I think it should always result in just one single schema rendered, right?

In case we would present this as multiple requests/responses, I think it shouldn't be an issue to incorporate support for this (once multiple possible representations are available in the AST) into #191.

**Comment by jmatsushita** [comment]
Would be great to have the first Sample used as the `application/json` when the main properties don't have values! It feels somehow that it would allow to separate concerns (schema/data) better.

**Comment by kylef** [comment]
These sample values have been shown in Apiary for a while.

<img width="230" alt="screen shot 2017-01-06 at 14 48 10" src="https://cloud.githubusercontent.com/assets/44164/21721193/29240054-d41f-11e6-9b80-28ca4a49a406.png">
