### ISSUE TITLE
Attributes - Underscore in example value attaches it to the param name

### ISSUE THREAD

**Issue by makkrnic** [apiaryio/api-blueprint#255]
When the example parameter value in the attributes contains an underscore it is parsed incorrectly and the parameter gets name in the form <param_name>:<example_value> and the example value doesn't exist

This code
```apib
+ Request (application/json)

    + Attributes
        + grant_type: refresh_token (string)
        + refresh_token: 8921...9387 (string)
```

produces this:
![selection_017](https://cloud.githubusercontent.com/assets/812401/9291456/5bc2632e-43c1-11e5-8275-dc05bdcfca19.jpg)

Expected outcome:
![selection_018](https://cloud.githubusercontent.com/assets/812401/9291467/3d8cd49c-43c2-11e5-8fcb-ce4aaef2dc28.jpg)

**Comment by pksunkara** [comment]
Since `_` is an MSON reserved character, you need to escape it using backticks.

```apib
+ `grant_type`: `refresh_token` (string)
```
