### ISSUE TITLE
Documentation generation 

### ISSUE THREAD

**Issue by fmielke** [apiaryio/api-blueprint#261]
Hi guys,

sorry, but I didn't find out anything about this topic. So, we have an own written REST API and want to generate only the documentation (not an API) with api blueprint. Is this possible?

Thank you!

Kind regards, Fabian

**Comment by pksunkara** [comment]
@fmielke You can use [apiary.io](http://apiary.io) to host your API documentation using the given API Blueprint or you can use [aglio](https://github.com/danielgtaylor/aglio] to host it yourself.

**Comment by zdne** [comment]
@fmielke 

The philosophy of API Blueprint and tool is to describe your API using the API Blueprint language and then use tools like Apiary or Aglio to generate documentation from it as @pksunkara mentioned. 

The benefit of this is you can use this description with other tools – for example you can test whether your API implementation matches the description using the [Dredd](https://github.com/apiaryio/dredd) testing tool. 

NOTE: there is no shortcut to generate description – API Blueprint – from your code. Personally, I believe that would be an anti-pattern. 

Does this answer your question?

**Comment by fmielke** [comment]
Yes, thanks @pksunkara and @zdne !
