### ISSUE TITLE
Optional path in endpoint

### ISSUE THREAD

**Issue by gnomeontherun** [apiaryio/api-blueprint#262]
I would like path variables to be optional. For example, we have an API structure like this.

```
GET /items - get a list of items
POST /items - create a new item

GET /items/{item_id} - get a specific item
PATCH /items/{item_id} - update an item
DELETE /items/{item_id} - delete an item
```

I would like to be able to combine the `POST` with the rest of the single item endpoints in my documentation, however due to the nature of having to specify a path parameter and not being able to make it optional.

The real issue is that there are collection endpoints (getting a list of resources), and resource endpoints (actions against a single resource), and right now I have to mix them.

Is there a way to do this currently, or is this a feature request?

**Comment by pksunkara** [comment]
You can group the resources.

```apib
# Group Items

## Item Collection [/items]

### List all Items [GET]
### Create Item [POST]

## Item [/item/{item_id}]

### Retrieve Item [GET]
### Update an Item [PATCH]
### Delete an Item [DELETE]
```

**Comment by gnomeontherun** [comment]
This is what I do already, but it doesn't flow well. I want to be able to do


```
# Group Items

## Item Collection [/items]

### List all Items [GET]

## Item [/item/{item_id}]

### Retrieve Item [GET]
### Create Item [POST]\
### Update an Item [PATCH]
### Delete an Item [DELETE]
```

**Comment by pksunkara** [comment]
You can add the url directly to the desired action to get it.

```apib
# Group Items

## Item Collection [/items]

### List all Items [GET]

## Item [/item/{item_id}]

### Retrieve Item [GET]
### Create Item [POST /items]
### Update an Item [PATCH]
### Delete an Item [DELETE]
```
