### ISSUE TITLE
Comments flagged as "unrecognized block"

### ISSUE THREAD

**Issue by Animeye** [apiaryio/api-blueprint#263]
HTML-style comments are correctly ignored when rendering, but a warning is flagged saying "Ignoring unrecognized block"

**Comment by zdne** [comment]
Hey @Animeye can you give us a (minimal) blueprint example? Thanks.

**Comment by Animeye** [comment]
It may only be doing this within certain sections.  Additionally, the warning does not appear when the page is first loaded -- it only appears once some content has been changed (even adding a blank line is sufficient).  The following should replicate the issue:

    FORMAT: 1A
    HOST: http://polls.apiblueprint.org/
    
    # Polls API
    
    
    
    # Data Structures

**Comment by pksunkara** [comment]
@Animeye Unfortunately `Data Structures` section does not allow any text at all except the MSON Named Types. Not even description text is allowed which is why the comment above is raising a warning.

**Comment by zdne** [comment]
@Animeye at the moment, the HTML-style comments can be used only where  description is expected

**Comment by brendensoares** [comment]
Sorry to resurrect this, but why doesn't the Data Structure section follow the [API Blueprint spec on section structure](https://apiblueprint.org/documentation/specification.html#def-section-structure)?
