### ISSUE TITLE
Handling multiple actions with the same method defined for the the same resource

### ISSUE THREAD

**Issue by ye** [apiaryio/api-blueprint#264]
While trying to compile this API blueprint, I am getting this error:

```bash
>> Line 187: action with method 'PUT' already defined for resource '/users/{id}' (warning code 2)
```

The offending API section looks like this:
![screen shot 2015-09-17 at 5 07 28 pm](https://cloud.githubusercontent.com/assets/133924/9946153/7bc04148-5d5f-11e5-87e0-f23576c75b02.png)

I am aware of the [multiple transactions under a single action](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#example-multiple-transaction-examples), however, I cannot seem to find a way to tuck in the small blobs of description for each different requests.

So my question is, how do we handle this case of multiple actions with the same method `PUT` in this case, for the same resource `/users` that different requests yielding different responses in this case?

Thanks.

**Comment by kylef** [comment]
Hi @ye,

You may use have [multiple examples](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#example-multiple-transaction-examples) under a single action as follows:

```apib
# Users [/users]
## Edit a User [PUT]

+ Request Editing the User's properties

        {"name": "Kyle"}

+ Response 204

+ Request Changing the User's password

        {"password": "athggsdsfsd3refdwesfrgse"}

+ Response 204
```

**Comment by leomperes** [comment]
@kylef and if I don't have a Request data, like:

```apib
+ Request A

+ Response 200 (application/json; charset=utf-8)

        {...}

+ Request B

+ Response 404 (text/html; charset=utf-8)

        {...}
```

I am getting warnings on those situations. How can I solve those warnings?

**Comment by kylef** [comment]
@leomperes if there is no request data or headers, then you can omit the request:

```apib
+ Response 200 (application/json; charset=utf-8)

        {...}

+ Response 404 (text/html; charset=utf-8)

        {...}
```

**Comment by leomperes** [comment]
Sorry @kylef, I was not clear, I would like to name the Responses because the second one has some importance...
