### ISSUE TITLE
Enum not working for response attributes

### ISSUE THREAD

**Issue by darkaeon10** [apiaryio/api-blueprint#268]
Hi, I've been able to successfully use enums to enumerate the possible values of a parameter, like so:

```apib
+ Parameters
    + status: 0 (enum[number], optional) - the status code
        + Members
            + 0 - success
            + 1 - error
```
![parameters](https://cloud.githubusercontent.com/assets/1049495/9985463/0ba66f2e-605f-11e5-9e5b-e7f6d6a6622a.png)

But when I do the same for a response attribute, it doesn't work. Refer to the snippet and screenshot below.

```apib
+ Response 200 (application/json)
    + Attributes
        + status: 0 (enum[number], optional) - the status code
            + Members
                + 0 - success
                + 1 - error
```

![response](https://cloud.githubusercontent.com/assets/1049495/9985465/0fe4e7dc-605f-11e5-94f0-46abc6bd9af8.png)

Any help would be greatly appreciated. Thanks!

**Comment by zdne** [comment]
Hey @darkaeon10 this is an issue with rendering body Attributes – as this feature is still in beta we are now working on full featured support for it. Please track the progress at https://github.com/apiaryio/api-blueprint/issues/191.

**Comment by darkaeon10** [comment]
@zdne alright! Sorry for the duplicate.

**Comment by zdne** [comment]
@darkaeon10 no worries!
