### ISSUE TITLE
Can one Action section contain multiple response subsections with same status code ?

### ISSUE THREAD

**Issue by sasikanthnimmagadda** [apiaryio/api-blueprint#270]
1. In API Blueprint, can we have One Action Section containing multiple Response Subsections with same same status code ? (200)

2. From the below documentation, it says we can have multiple response subsections with different http status codes. Does it mean we cannot have multiple responses with same status code (200) ?

>Reference: 
>> https://github.com/apiaryio/api-blueprint/blob/format-1A/API%20Blueprint%20Specification.md#43144-action-response-section
 " One Action Section can contain one or more different (that is with different HTTP Status codes) Response Subsections. "

**Comment by zdne** [comment]
Multiple responses with the same status code are OK as long as either media type differs or they are part or another transaction example (=separated by requests)

For example:

```apib
- response 200 (application/json)
- response 200 (text/plain)
- response 200 (application/xml
```

or 

```apib
- request A
- response 200
- request B
- response 200
```

Does this clarify?

**Comment by sasikanthnimmagadda** [comment]
Thanks for the clarification
