### ISSUE TITLE
Specify not URI parameters

### ISSUE THREAD

**Issue by fabiomassimo** [apiaryio/api-blueprint#273]
For POST request to a resource I'd like to declare parameters that will be part of the request's body with similar syntax we have for URI parameters.

For example:

```
## Device [/devices/]

### Create a New Device [POST]

Create a new device instantiation. 
Note: any previous registration with same token will be replaced.

+ Parameters
  + uuid (string, required) - One-time unique identifier
  + something_else (string) - Something else not required
```

This syntax will raise a warning because `uuid` and `something_else` are not specified in the URI but I want to declare them as parameters to my request body.

Am I missing some syntax declaration?

**Comment by pksunkara** [comment]
You can use the [Attributes section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section) to define them.
