### ISSUE TITLE
How to escape usage of a reserved keyword ?

### ISSUE THREAD

**Issue by jmartigny** [apiaryio/api-blueprint#275]
Hi,
I am developing an API for which one of the resource name is "Groups".

Obviously I am getting some errors while writing the documentation since I'm using the reserved keyword "Group". Since "Groups" is a term that is deeply implanted in our business model and has been for many years, it's out of the question to have our API use any other term.

Is there any way to escape a word in blueprint so that it is not interpreted as a reserved keyword ?

**Comment by pksunkara** [comment]
@jmartigny Hey, Can you give us an example blueprint which reproduces this? I think we know what you are talking about, but we want to make sure.

**Comment by jmartigny** [comment]
Hi, I think it was a misunderstanding on my side that was causing my issue. I cannot reproduce it anymore now that I am more familiar on how blueprint is structured.
