### ISSUE TITLE
Attributes via data structures broken with last update

### ISSUE THREAD

**Issue by jeremytm** [apiaryio/api-blueprint#280]
After the fix for issue #232 our attributes no longer show. This is only affecting attributes created using data structures. Normal inline attributes appear to be OK.

See the [official Apiary Data Structures example](https://github.com/apiaryio/api-blueprint/blob/master/examples/10.%20Data%20Structures.md). 

To confirm, view the "Create a coupon" interactive area, we should see the `Coupon Base` attributes listed, and we should see the `Coupons` attributes listed under the response. We no longer see either of these lists.

**Comment by zdne** [comment]
The regression issue on Apiary has been fixed. As I have mentioned here https://github.com/apiaryio/api-blueprint/issues/232#issuecomment-155065074

**Comment by jeremytm** [comment]
Looks great now, thanks :)
