### ISSUE TITLE
Underscores in Query and Parameters not working

### ISSUE THREAD

**Issue by Clar64** [apiaryio/api-blueprint#281]
Hi!

I've got an issue with fields with underscores in the query and parameters list. I had a look at the other tickets related to this: #202, #224, #255 but the fixes suggested there (`field_name`) does not seem to work in this case.

My text:

![apiarybug1](https://cloud.githubusercontent.com/assets/1788149/11034038/f0259794-86f0-11e5-9a46-c85a5f03948f.PNG)

The error is: Parameter 'transaction_id : Filter on the... ' not specified...

When I add the back ticks to both the query parameters and parameter list, the parameter list entry gets another error:

![apiarybug2](https://cloud.githubusercontent.com/assets/1788149/11034098/75684c44-86f1-11e5-8458-2f949d0da271.PNG)

(The back ticks are very small on the screen shot - sorry about that.)

So neither way is working right now. Am I doing something wrong? I'd appreciate help.

**Comment by pksunkara** [comment]
Hey @Clar64, you are right in that you should be escaping the parameter name using backticks. But we have a small bug relating to this as documented at https://github.com/apiaryio/drafter/issues/123. Please follow the bug there. Thanks.

**Comment by kamihouse** [comment]
Guys we can do this:

```apib
+ Parameters
     + `grant_type`: `refresh_token` (string, required) - Tipo de concessão
```

Works great!
