### ISSUE TITLE
multiple examples with different parameter value

### ISSUE THREAD

**Issue by hs3180** [apiaryio/api-blueprint#283]
We have multiple examples for different pair of request body and response now, like:

    + Request
      ...
    + Response xxx
      ...

But it could just set different request body. sometimes, I want to show examples that use different request parameters in query. I've tried following:

    + Parameters
      para: ...
    + Response xxx
      ...
    + Parameters
      para: ...
    + Response xxx
      ...

It will just overwrite parameters. What I really want is that show multiple examples with different parameters and response.

**Comment by pksunkara** [comment]
@hs3180 We are already tracking this feature request at #58. If you go through it, you can see our proposed changes to API Blueprint. Please follow the updates there.
