### ISSUE TITLE
Escape special characters in Array data structure

### ISSUE THREAD

**Issue by romainPellerin** [apiaryio/api-blueprint#285]
Hi Apiary team,

first, my strong congrats for all the work around API Blueprint and hosting!

I experience a new issue since a few days on the rendering (right panel of apiary.io) for this kind of data structure:

```markdown
## Credentials (object)
+ uid: e35be76-rfc9-45d3-8783-731d66b18f48 (string, required) - id of the user
```

This is parsed by your engine as:

**ATTRIBUTES**
```
name     value           description
uid      e35bed76        rfc9-45d3-8783-731d66b18f48 (string, required) - id of the user
```

So it takes the first "-" as the delimiter of attribute's description.
Hope you can fix this asap for a better readability on your API hosting.

Best.

**Comment by pksunkara** [comment]
Hey, you need to escape the value with backticks since `-` is a reserved character.

```
`e35be76-rfc9-45d3-8783-731d66b18f48`
```

**Comment by romainPellerin** [comment]
Thanks it works.
Is it a new requirement? In fact, this was not mandatory a few days ago.

**Comment by kylef** [comment]
@romainPellerin It's always been apart of the API Blueprint and MSON specification, however tooling may have allowed this though previously.

Without this there is really no way to determine where the description separator is in the following example:

```apib
## Credentials (object)
+ uid: e35be76-rfc9-45d3-8783-731d66b18f48 (string, required) - id of the user-name
```

**Comment by romainPellerin** [comment]
Yes it works but the CURL command generated keeps the character **`** and then modifies the content expected for the request:

```curl
curl --include \
     --request POST \
     --header "Content-Type: application/json" \
     --data-binary "[\"uid: `e35be76-rfc9-45d3-8783-731d66b18f48`\"]" \
'http://host/api/service'
```

**Comment by pksunkara** [comment]
Unfortunately, I cannot reproduce this. Please look at docs.mson.apiary.io.

I am getting the following:

```
curl --include \
     --request GET \
     --header "Content-Type: application/json" \
     --data-binary "[{\"id\":\"abcd-efgh\"}]" \
'http://private-2a15-mson.apiary-mock.com/user'
```
