### ISSUE TITLE
Embedded Assets

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint#29]
Provide a facility to embed an asset inside another asset while keeping the actual asset media-type opaque. For example re-use a message-body asset inside another message-body (e.g. an item inside its collection). 

Possibly related issues: 
- #9 
- #25 
- #28

**Comment by adambuczynski** [comment]
I'm going back and forth a bit in the documentation, examples, this issue and severak other issues in this repo, but I still can't figure out how to reference an array of JSON data in my API definition.

Can someone provide a clear example, with or without MSON, using Model or Attributes or Data Structures or whichever, as long as I can define one model somewhere, and then reference it for the body of a response, either for a targeted GET (single model) or collection GET (array of models)?

Thanks!

**Comment by kylef** [comment]
@adambuczynski You can find an example at https://apiblueprint.org/documentation/advanced-tutorial.html#data-structures. Where you can reference the data structure as follows for a single request/response:

```apib
+ Request (application/json)
    + Attributes (Question)

+ Response 200 (application/json)
    + Attributes (Question)
```

A collection of Question:

```apib
+ Response 200 (application/json)
    + Attributes (array[Question])
```

**Comment by adambuczynski** [comment]
@kylef thanks, that's when using data structures.
But as far as I understand, I need to define these data structures on top.

With models, I can define them for a specific endpoint, and then reuse them in the response body. Can I reference a collection of models somehow?

**Comment by adambuczynski** [comment]
I think I've figured it out now, I just define the data structure under Attributes of the named endpoint, and then I can use the named endpoint as a reference in attributes for the response, e.g.:

```
## Item [/item]

+ Attributes
    + name: `Some item` (string)
    + date: `2015-08-05T08:40:51.620Z` (string)

### View item [GET /item/{itemId}]

+ Parameters
    + itemId (ObjectId, required)

+ Response 200 (application/json)
    + Attributes (Access Log)

### List items [GET /item]

+ Response 200 (application/json)
    + Attributes (array[Access Log])
```

This is what I was after.

**Comment by kylef** [comment]
@adambuczynski You can find an example at https://apiblueprint.org/documentation/advanced-tutorial.html#data-structures. Where you can reference the data structure as follows for a single request/response:

```apib
+ Request (application/json)
    + Attributes (Question)

+ Response 200 (application/json)
    + Attributes (Question)
```

A collection of Question:

```apib
+ Response 200 (application/json)
    + Attributes (array[Question])
```
