### ISSUE TITLE
Data Structure for Entire Response?

### ISSUE THREAD

**Issue by bitdivision** [apiaryio/api-blueprint#294]
I don't see any way to include a data structure as the entire response of an action. I'm essentially hoping to refactor a blueprint so that error responses don't have to be repeated for every endpoint.

e.g.

I currently have a lot of these:
```
+ Response 401 (application/json)

    + attributes (error)

    + body
            
            {
                "title": "Unauthorized",
                "description": "You do not have authorization to access this resource."
            }
```

on multiple endpoints and I'm hoping there's a way to factor them out into a single one and use something like 

```
+ Response 401 (UnauthorizedError)
```

Is this possible?

**Comment by zdne** [comment]
You can do something like this: 

```apib

## Error (object)
- title (string)
- description (string)

## UnauthorizedError (Error)
- title: Unauthorized
- description: You do not have authorization to access this resource.


# Group Lorem
## Ipsum [/ipsum]
### Retrieve [GET]
- response 200 (applciation/json)
- response 401 (application/json)
    - attributes (UnauthorizedError)
```

Does this help?

**Comment by bitdivision** [comment]
Okay. That's a little better. Thanks @zdne
