### ISSUE TITLE
Remove empty query variable from request when writing blueprint this way

### ISSUE THREAD

**Issue by hassansin** [apiaryio/api-blueprint#312]
I am using the Polls api to show my use case. It has one Resource section and under it two Action sections with different URI. It seems valid to me and the drafter doesn't complain either. 

```api-blueprint

FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Polls

## Questions [/questions]

### List all questions [GET /questions{?page}]

+ Parameters
    + page (optional, number) - The page of questions to return
            
+ Response 200

## View a question detail  [GET /questions/{question_id}]

+ Parameters
    + question_id (required, number, `1`) ... ID of the Question in form of an integer

+ Response 200 
```

But when I leave the `page` query empty, it still includes the default value of `page=page` in the request:

![image](https://cloud.githubusercontent.com/assets/4618044/13096626/f542c5d8-d544-11e5-8cd7-80712e0bea01.png)

![image](https://cloud.githubusercontent.com/assets/4618044/13096644/261706a6-d545-11e5-91c8-f7c6e427b426.png)

**Comment by netmilk** [comment]
Hey @hassansin! Thank you very much for reporting this. We'll track it as a bug internally and it will be scheduled for fixing soon.

**Comment by hassansin** [comment]
Awesome. Thanks!
