### ISSUE TITLE
How do I get the docs to show array response schema correctly?

### ISSUE THREAD

**Issue by akutz** [apiaryio/api-blueprint#313]
I think this question is linked to #237. Take the following example:

> ## Get [GET]
> Gets information about all volumes for a service.
> 
> + Response 200 (application/json)
> 
>     + Attributes (array)
>         
>         + (Volume)
> 
>     + Body
> 
>             [
>                 {
>                     "id":     "vol-000",
>                     "name":   "Volume-000",
>                     "size":   10240,
>                     "fields": {
>                         "priority": 2,
>                         "owner":    "sakutz@gmail.com"
>                     }
>                 },
>                 {
>                     "id":     "vol-001",
>                     "name":   "Volume-001",
>                     "size":   10240,
>                     "fields": {
>                         "priority": 2,
>                         "owner":    "sakutz@gmail.com"
>                     }
>                 }
>             ]

Here is the documentation this produces:

![image](https://cloud.githubusercontent.com/assets/101085/13158697/bc332ce6-d653-11e5-86b5-618798b958e4.png)

I would like the `Attributes` section to do a better job illustrating that there is an array of `Volume` objects being returned. Is there a way I can define the response so that this occurs? Thank you :)

**Comment by zdne** [comment]
Hi @akutz this should be fixed soon with #254 and #191

**Comment by neerajjain92** [comment]
@zdne How soon? it's not yet fixed.
