### ISSUE TITLE
comments on request body

### ISSUE THREAD

**Issue by Alexorz** [apiaryio/api-blueprint#316]
Hello guys, is there any syntax for adding some comments into the request body?

Sometimes I need to make some notes on some params in the JSON of POST request body,  just like this:
````
+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "answer": "JavaScript",     // value of `answer` must be one of these options: "Swift", "Python", "Objective-C", "Ruby", "JavaScript"
        }
````

But I found it will make the request body becomes an invalid JSON string in **apiary.io** or in **dredd**.

Here is the request body which was generated by apiary.io, it didn't cut out the content after `//`:
![image](https://cloud.githubusercontent.com/assets/660581/13435476/826f29bc-e015-11e5-8fd8-8fc62bea110b.png)

And dredd threw error:
 `fail: body: Can't validate. Expected body Content-Type is application/json but body is not a parseable JSON: Parse error on line 1:`

So, Is there any solutions?
Or, am I doing right?

Thank you.

**Comment by kylef** [comment]
We can go one step further and actually document it using [MSON](https://apiblueprint.org/documentation/mson/tutorial.html) and explicitly mark this value as an enum, for example:

```apib
+ Request (application/json)
    + Attributes
        + question: `Favourite programming language?` (required)
        + answer: JavaScript (enum, required)
            + Swift
            + JavaScript
            + Ruby
```

Using MSON, you can attach descriptions and other type-information.

With our new beta for attributes in Apiary ([opt-in](https://github.com/apiaryio/api-blueprint/issues/191#issuecomment-178044764)), you can view this as follows:

![screen shot 2016-03-01 at 18 08 53](https://cloud.githubusercontent.com/assets/44164/13436769/ada42070-dfd8-11e5-8fcf-13a1d22d1a9a.png)

This will also generate a matching JSON Schema:

![screen shot 2016-03-01 at 18 10 51](https://cloud.githubusercontent.com/assets/44164/13436818/f7ffaa72-dfd8-11e5-8afc-1307049a7ce4.png)

And render the example JSON payload from the example values:

![screen shot 2016-03-01 at 18 10 55](https://cloud.githubusercontent.com/assets/44164/13436825/036602a8-dfd9-11e5-99d1-788db4e83056.png)

Does this answer your question?

**Comment by kylef** [comment]
Also want to point out, using the `enum` MSON syntax, Dredd can then improve it's validation to enforce that values are inside the enum.

**Comment by Alexorz** [comment]
It works, that is pretty cool. Thank you :)
And maybe I should read the doc more attentively next time...
