### ISSUE TITLE
Nullable type doesn't work within method declaration

### ISSUE THREAD

**Issue by danilvalov** [apiaryio/api-blueprint#320]
I'm trying to use ![nullable type](https://github.com/apiaryio/mson/blob/master/examples/nullable.md) in my mson following sample in the documentation, but it fails with semantic error.

![](http://cl.ly/0D3G300q070a/Image%202016-04-13%20at%204.50.52%20PM.png)

Please help me to figure out what's wrong with my mson and how to make correct documentation for my use case?

Thanks!

**Comment by kylef** [comment]
Hi @danilvalov, Apiary isn't using the latest version of the API Blueprint Parser which adds support for nullability.

Apiary does have a beta for improve attributes rendering, which includes support for nullability. You can find more about the beta at https://github.com/apiaryio/api-blueprint/issues/191#issuecomment-178044764 along with how to join it.

Regards,

Kyle

**Comment by kylef** [comment]
I just want to point out that this has now been deployed to Apiary.

As an example, you can use nullable like the following:

```apib
+ Response 200 (application/json)
    + Attributes
        + example1 (string, optional, nullable) - An example optional nullable string
        + example2: value (string, optional, nullable) - An example optional nullable string with a sample value
```

Where this would result in an example payload of the following:

```json
{
  "example1": null,
  "example2": "value"
}
```

Along with the following JSON schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "example1": {
      "type": [
        "string",
        "null"
      ],
      "description": "An example optional nullable string"
    },
    "example2": {
      "type": [
        "string",
        "null"
      ],
      "description": "An example optional nullable string with a sample value"
    }
  }
}
```

The table of attributes in [Apiary doesn't yet mention that the value is nullable](https://github.com/apiaryio/attributes-kit/blob/master/STATUS.md#35-type-definition), but this is coming.

<img width="322" alt="screen shot 2016-06-20 at 17 46 45" src="https://cloud.githubusercontent.com/assets/44164/16202754/03ae5098-370f-11e6-8f20-498966db590c.png">

**Comment by patricksmms** [comment]
This is now visible, in [ApiaryUI](https://blog.apiary.io/ApiaryUI):
![image](https://user-images.githubusercontent.com/17434816/81840320-1e328500-9549-11ea-9598-d126c68df623.png)
