### ISSUE TITLE
SLA Section Request

### ISSUE THREAD

**Issue by peter-quinton** [apiaryio/api-blueprint#321]
Feature Request: 
A section that you can put a service level agreement into.  This would be ideally be a child of the "Action" section. 

My apologies if this is the wrong place for a feature request.

**Comment by zdne** [comment]
Can't you just put the SLA notice in the Action's description like so:

```apib
# My Resource [/r]

## Action A [GET]
Lorem Ipsum.

### SLA
SLA Ipsum.

- Response 200
```

**Comment by peter-quinton** [comment]
Thank you for your response, I tried your suggestion and aglio renders that perfectly, however protaganist puts it into a element of type copy.  I was hoping to be able to use the SLA datastructure programatically... 

If I use an Attributes section with an object body (not MSON) it shows up under en element type of dataStructure in the content.meta property.  However, it doesn't render for humans using aglio.  

```
{
  "attributes": {
    "data": {
      "element": "dataStructure",
      "content": [
        {
          "element": "object",
          "meta": {
            "description": "        {\n          \"SLA\": {\n            \"NRappName\": \"hello\",\n            \"endpiont\": \"/ships/{shipId}\",\n            \"verb\": \"GET\",\n            \"responseTime\": 250,\n            \"rps\": 500\n          }\n        }\n"
          }
        }
      ]
    }
  }
}
```

If I could use it programmatically and have it render  via aglio that would be ideal.    If you have any other suggestions I'd love to see them.

**Comment by zdne** [comment]
Gotcha. I would say that the only way to process this right now is to introspect every copy element.

**Comment by kylef** [comment]
There's an open issue regarding Aglio's lack oif rendering for data structures (https://github.com/danielgtaylor/aglio/issues/103) unfortunately Aglio isn't that maintaned these days (https://github.com/danielgtaylor/aglio/commit/0cef09ab83d680689bcadf53aa45fc7bca3b5af3) so I think it is unlikely this will move much. However there are some alternative API Documentation generators from API Blueprint that have came along, and there is the [Apiary](https://apiary.io) documentation rendered which support rendering data structures.
