### ISSUE TITLE
Attributes with array of objects produce incomplete schema

### ISSUE THREAD

**Issue by agougousis** [apiaryio/api-blueprint#328]
The following part of my text file:

+ Response 200 (application/json)

	+ Attributes (object)		
		- nodes (array[object])
			- id: 4 (number)
			- sname: `Chromista`  (string) - The scientific name
			- rank: `Kingdom` (string) - The taxonomic rank of the scientific name
			- authorship: `noworms, 1603` (string) - Authorship information about the scientific name

	+ Body 
	
			{
				"nodes": [
					{
						"id": "1",
						"sname": "Animalia",
						"rank": "Kingdom",
						"authorship": "noworms, 1603"
					},
					{
						"id": "2",
						"sname": "Archaea",
						"rank": "Kingdom",
						"authorship": "noworms, 1603"
					},
					{
						"id": "3",
						"sname": "Bacteria",
						"rank": "Kingdom",
						"authorship": "noworms, 1603"
					},
					{
						"id": "4",
						"sname": "Chromista",
						"rank": "Kingdom",
						"authorship": "noworms, 1603"
					},
					{
						"id": "5",
						"sname": "Fungi",
						"rank": "Kingdom",
						"authorship": "noworms, 1603"
					}
				],
				"hasMore": 1
			}

Produces this HTML:

![pic1](https://cloud.githubusercontent.com/assets/5471589/15178824/a351890c-1780-11e6-9d7e-bf352ddd13ac.jpg)

The part of schema inside the ""nodes" is missing! Why?
I have also tried to use data structures but the schema remains incomplete.

**Comment by pksunkara** [comment]
@agougousis Can you try the following?

```
nodes (array[object], fixed)
```

**Comment by agougousis** [comment]
Ok! Though I haven't found yet where this "fixed" world came from, now the schema is complete.
However, it seems that the produced schema is not right. 
The schema produced is:

![pic3](https://cloud.githubusercontent.com/assets/5471589/15179872/ebcdd806-1786-11e6-906e-0eeee85b536c.jpg)

and the correct schema should be:

![pic4](https://cloud.githubusercontent.com/assets/5471589/15179885/fbf24bf4-1786-11e6-87f9-22a90e777ca3.jpg)

Am I wrong?

**Comment by pksunkara** [comment]
Can you try this?

```
+ nodes (array, fixed)
    + (object)
        + id: 4 (number)
```

**Comment by agougousis** [comment]
Yeap! A lot better! I didn't think that "anonymous" objects can be defined! 
I am not sure, but I think that the brackets marked in the following screenshot should not be there. What do you think?
![schema](https://cloud.githubusercontent.com/assets/5471589/15209200/79fbd374-1838-11e6-81a8-ad2621e9b1bf.png)

**Comment by w-vi** [comment]
@agougousis The brackets are correct as items is an array of possible types

**Comment by agougousis** [comment]
I don't remember very well the rules, but in http://jsonschema.net/ (a quick and dirty solution that I use from time to time) when i give the json data as input it gives me the schema without these brackets.

**Comment by kamihouse** [comment]
Use a `fixed-type` for this:

``` markdown
+ nodes (array, fixed-type)
    + (object)
        + id: 4 (number)
```

**Comment by tomacf** [comment]
+1 for the fixed-type

 fixed - instance of this type structure and values are fixed. This attribute propagates to Nested Member Types.

 fixed-type - instance of this type structure is fixed, value is not. This attribute does not propagate to Nested Member Types.


https://apiblueprint.org/documentation/mson/specification.html#353-type-attribute
