### ISSUE TITLE
Can break value easily

### ISSUE THREAD

**Issue by kirkstrobeck** [apiaryio/api-blueprint#329]
https://github.com/apiaryio/api-blueprint/blob/8cb625fa6463800a63345c30fa994d35af1df518/API%20Blueprint%20Specification.md#example-14

This will break

```md
+ author: "47.622288,-122.336494" (string) - Author of the blog post
```

**Comment by kylef** [comment]
@kirkstrobeck Since your sample value contains a dash, it must be escaped with backticks. As per the [MSON Specification: Reserved Characters](https://apiblueprint.org/documentation/mson/specification.html#6-reserved-characters--keywords)

```apib
+ author: `47.622288,-122.336494` (string) - Author of the blog post
```
