### ISSUE TITLE
Supporting JSON-RPC and RPC-style API

### ISSUE THREAD

**Issue by SvyatoslavVasiliev** [apiaryio/api-blueprint#333]
Hi there, 
I really need such functionality. I designed API according [JSON RPC 2.0 specification](http://www.jsonrpc.org/specification) and now I have to create public documentation. But there is not instrument to solve such issue. 
I hope your tool will support RPC-styled API especially JSON-RPC, in view this niche is empty right now.

**Comment by zdne** [comment]
Duplicate to #83
