### ISSUE TITLE
Conditional parameters based on another parameter's value

### ISSUE THREAD

**Issue by pararang** [apiaryio/api-blueprint#339]
What is the format for parameters if I have condition where some parameters can be changed based on another param's value. Eg: I have payment methods: paypal, bank transfer, etc.
- `+ amount (required, number, `1200`) ... charge amount`
- `+ method (required, string, `paypal`) ... payment method`
   - `+ Values`
        - + `paypal`
        - + `bank transfer`
        - + `etc`

if method's value is "paypal", then my service need additional param:
- `+ email (required, string, `user@email.com`) ... user's paypal account`

if method's value is "bank transfer", then my service need additional params:
- `+ bank_name (required, string, `Panama National Bank`) ... user's bank`
- `+  bank_account (required, number, `3445315-XXX`) ... user's bank account`

**Comment by kylef** [comment]
Hi @pararang,

This isn't possible at the moment, but it is something on our radar and in [our roadmap](https://github.com/apiaryio/api-blueprint/wiki/Roadmap). We're planning to make parameters use [MSON](https://apiblueprint.org/documentation/mson/tutorial.html), which would allow you to use [one of](https://apiblueprint.org/documentation/mson/specification.html#52-one-of-type) which should allow you to achieve this.

```apib
+ Parameters
    + amount: 1200 (number) - Charge Amount
    + One Of
        + Properties
            + method: paypal (required, fixed)
            + email (required)
        + Properties
            + method: bank (required, fixed)
            + `bank_name` (required)
            + `bank_account` (required)
```

<img width="266" alt="screen shot 2016-06-29 at 10 49 52" src="https://cloud.githubusercontent.com/assets/44164/16448023/3cb88b22-3de7-11e6-8c13-0c8a1d69a368.png">

Please track this in https://github.com/apiaryio/api-blueprint-rfcs/pull/3 / https://github.com/apiaryio/api-blueprint/issues/286

**Comment by webmato** [comment]
+1
`One Of` for `Parameters` would be very useful. I need it right now.
