### ISSUE TITLE
Formatted output on GitHub

### ISSUE THREAD

**Issue by preraksola** [apiaryio/api-blueprint#340]
Is it possible to show the `.apib` files in a formatted way on GitHub instead of the raw text?
I am looking for something similar to what we see during the preview while creating the documentation on the website.
I know I have the public URL, whose link I can provide, but I prefer it to be embedded in the Git instead of opening an external window.

Let me know if anything can be done to achieve this.

Prerak

**Comment by pksunkara** [comment]
@preraksola Unfortunately Github doesn't allow custom HTML rendering as part of syntax highlighting. There were some discussions on it, but this requires far more effort and collaboration with github development team.

**Comment by pksunkara** [comment]
We can keep this open for future discussions.

**Comment by kylef** [comment]
I don't think there is much we can do here, as there hasn't been any movement on this I am going to close the issue as I am triaging a lot of the open issues.
