### ISSUE TITLE
Required Parameter Subset

### ISSUE THREAD

**Issue by webmasterjunkie** [apiaryio/api-blueprint#341]
Hi,

I am documenting an API that has a required subset of parameters. As an example, you have to specify one of the following subsets:

+ start_date
+ end_date

OR 

+ text_date

How can I go about getting this documented so CI doesn't fail tests trying to require all 3?:

+ Parameters
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`
    + text_date: this+week (enum[string])
        + this+hour
        + last+hour
        + today
        + yesterday
        + this+week
        + last+week
        + this+month
        + last+month
        + this+year
        + last+year

Any help would be appreciated.

Thanks

**Comment by kylef** [comment]
This isn't possible yet, please check my comment at https://github.com/apiaryio/api-blueprint/issues/339#issuecomment-229310519 regarding this feature.
