### ISSUE TITLE
Apiary Blueprint Docs: Text selection in Firefox

### ISSUE THREAD

**Issue by peterpp** [apiaryio/api-blueprint#343]
In Firefox, it is not possible to select text in rendered documentation. Whole page is moved instead. I looks like wrong implementation of touch controls.

**Comment by nadade** [comment]
Thanks for the report! Can you please share your OS type and version and the Firefox version? Feel free to contact us at support [at] apiary [dot] io or feel free to continue the discussion here.

**Comment by peterpp** [comment]
I have OS X 10.11.5, Firefox 47.0.1. I also tried to restart Firefox in safe mode (without plugins) to ensure that problem is not there.

**Comment by nadade** [comment]
Thanks for the details! I filed the bug report and we'll keep you posted on the progress.

**Comment by kylef** [comment]
Hi, this problem should be solved in our new ApiaryUI renderer. Please check out https://blog.apiary.io/ApiaryUI for more information.

If you have any further bug reports that are specific to Apiary rendered documentation please reach out to Apiary support. This repository and issue tracker is tracking the API Blueprint specification.
