### ISSUE TITLE
Highlight code snippet

### ISSUE THREAD

**Issue by goraniliev** [apiaryio/api-blueprint#347]
I have been using apiary for HTTP Rest endpoints and it is really great!

Now I wanted to add the websocket functionalities, but could not find an easy way. Seems like it is not supported yet. So, I copy-pasted code snippet into the documentation and it looks like a regular text. Is there a way to format the code snippet and highlight the syntax. It is written in Python, if that is relevant.

Thank you!

**Comment by pksunkara** [comment]
I am sorry, but I don't think we support syntax highlighting in the plain markdown of an API's documentation. Can you send an email to support@apiary.io about this?

Thanks.

**Comment by talkoren** [comment]
+1

**Comment by ryanwinchester** [comment]
duplicate of #315?
