### ISSUE TITLE
void-variable complication-error-regexp-alist-alist

### ISSUE THREAD

**Issue by cokleisli** [apiaryio/api-blueprint#350]
I'm getting the following error when launching emacs as follows:

`emacs bar.apib`

`Debugger entered--Lisp error: (void-variable compilation-error-regexp-alist-alist)
  (member (quote (apib "^\\(?:warning\\|error\\):.+?line \\([0-9]+\\), column \\([0-9]+\\) - line \\([0-9]+\\), column \\([0-9]+\\).*$" apib--error-filename 3 4)) compilation-error-regexp-alist-alist)
  (if (member (quote (apib "^\\(?:warning\\|error\\):.+?line \\([0-9]+\\), column \\([0-9]+\\) - line \\([0-9]+\\), column \\([0-9]+\\).*$" apib--error-filename 3 4)) compilation-error-regexp-alist-alist$
  (progn (if (member (quote (apib "^\\(?:warning\\|error\\):.+?line \\([0-9]+\\), column \\([0-9]+\\) - line \\([0-9]+\\), column \\([0-9]+\\).*$" apib--error-filename 3 4)) compilation-error-regexp-alis$
  (eval-after-load "compilation" (progn (if (member (quote (apib "^\\(?:warning\\|error\\):.+?line \\([0-9]+\\), column \\([0-9]+\\) - line \\([0-9]+\\), column \\([0-9]+\\).*$" apib--error-filename 3 4)$
  (let ((delay-mode-hooks t)) (markdown-mode) (setq major-mode (quote apib-mode)) (setq mode-name "apib") (progn (if (get (quote markdown-mode) (quote mode-class)) (put (quote apib-mode) (quote mode-clas$
  (progn (make-local-variable (quote delay-mode-hooks)) (let ((delay-mode-hooks t)) (markdown-mode) (setq major-mode (quote apib-mode)) (setq mode-name "apib") (progn (if (get (quote markdown-mode) (quot$
  apib-mode()
  set-auto-mode-0(apib-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer bar.apib> "~/Development/blueprints/bar.apib" nil nil "~/Development/blueprints/bar.apib" nil)
  find-file-noselect("~/Development/blueprints/bar.apib" nil nil t)
  find-file("~/Development/blueprints/bar.apib" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
`

**Comment by pksunkara** [comment]
@cokleisli Can you give us the blueprint? I don't exactly know what the issue here is. @w-vi uses emacs though, so maybe he will know.

**Comment by w-vi** [comment]
@cokleisli : I guess we can continue in the https://github.com/w-vi/apib-mode repo where this question really belongs. https://github.com/w-vi/apib-mode/issues/3
