### ISSUE TITLE
Accept any value in POST JSON

### ISSUE THREAD

**Issue by maciejburda** [apiaryio/api-blueprint#355]
Is there any way to make POST request of API Blueprint to accept any value?

Right now I have:

```
### Google [POST]
Login with Google

+ token (string) - google token

+ Request (application/json)
      {
          "token": "google"
      }

+ Response 200 (application/json)
      {
        "token": "xyz",
      }

```
And nothing apart from exactly the same body as as described is being consumed by Drakov.

for instance
token = "google" -> works
token = "realGoogleToken" -> doesn't work

I've found that's possible for GET requests, but no idea how to make it work for POST and headers.

**Comment by maciejburda** [comment]
```
### Google [POST]
Login with Google

+ token (string, required) - google token

+ Request (application/json)

    + Attributes

        + token: "google" (string, required)

+ Response 200 (application/json)
      {
        "token": "xyz",
      }```

solves the issue

**Comment by pksunkara** [comment]
@maciejburda We are working on the idea of adding authentication as discussed here. https://github.com/apiaryio/api-blueprint/issues/11
