### ISSUE TITLE
Support query parameter with multiple values

### ISSUE THREAD

**Issue by nalinchhajer1** [apiaryio/api-blueprint#356]
Hi,
I need a support for below kind of end-point

/products?storeId=24&storeId=45&brandId=1234&brandId=12123

/products?storeId=24&storeId=45&brandId=1234

/products?storeId=24&storeId=45&brandId=1234&categoryId=8889

where storeId, brandId and categoryId  are array(string) and are optional.

I have noticed that https://tools.ietf.org/html/rfc6570#section-2.4.2 has schema for it, bit it is not supported in Apiary. User should be able to try above given end-points in machine column in apiary. Please help.

**Comment by pksunkara** [comment]
We are working on an RFC to allow support for this. You can read this [comment](https://github.com/apiaryio/api-blueprint-rfcs/pull/3#issuecomment-235600579) and check the related discussion.

**Comment by pksunkara** [comment]
I am closing this in favour of that issue.
