### ISSUE TITLE
How can I send a image binary as a response?

### ISSUE THREAD

**Issue by wangcansunking** [apiaryio/api-blueprint#357]
As the title saying, how can I send image with the response?

**Comment by pksunkara** [comment]
AFAIK, there is no current way of doing this.

**Comment by zdne** [comment]
@wangcansunking you can specify the media type in the response e.g. `- Response 200 (img/png)` however there si no way to provide an example for binary data in API Blueprint. Hint: you can also specify some metadata (headers) in the example response, these may include `Content-Length` etc. 

Workaround would be to return a response with the link to the binary resource.

**Comment by zdne** [comment]
Also you can use base64 encoding. Finally, this could be addressed in #20

**Comment by wangcansunking** [comment]
Now I use redirect as the solution.
