### ISSUE TITLE
How to reuse RESPONSE in Apiary

### ISSUE THREAD

**Issue by zatziky** [apiaryio/api-blueprint#358]
Is there a way how to reuse RESPONSE in Apiary? I think that [Data Structures][1] are not the correct way but I can't find anything else...

  [1]: https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-data-structures

**Comment by w-vi** [comment]
What do you mean by reusing response? If you want to specify just one response and then refer to it in some of the methods then that is not possible, there is no syntax for it. If you want to reuse the content of response there you can use the Data Structures as you already mentioned.

**Comment by zatziky** [comment]
@w-vi thanks for the answer. I would like to reuse this part:

```
+ Response 201 (application/json)
    
    + Body
    
            {
                "message": {
                    "id": "MESSAGE_ID"
                    "recipient" : {
                        "id": "USER_ID"
                    }
                }
            }
```

Can you tell if it's possible to reuse it at least partially?

**Comment by w-vi** [comment]
Would something like the following example work for you?

```apib
# A

## A [/a]

### Get A [GET]

+ Response 201 (application/json)

    + Attributes (GenericRes)


## B [/b]

### Get B [GET]

+ Response 201 (application/json)

    + Attributes (GenericRes)


# Data Structures

## GenericRes(object)
+ message (object)
    + id : MESSAGE_ID (string) - Message ID
    + recipient(object)
      + id : USER_ID (string)- User ID

```

**Comment by zatziky** [comment]
Thank you @w-vi , that's exactly what I needed!
