### ISSUE TITLE
Property Member Constraints

### ISSUE THREAD

**Issue by zatziky** [apiaryio/api-blueprint#359]
Is there a way how to specify limits, ranges and other constraints to property members? 

From [Attributes](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section) I couldn't find a way. 

Particularly, I would to set an upper limit on a text length:

```
### TextContent (Content)

+ type: "text"

+ payload (string, MAX_LENGTH:320) - Text to be sent. 
```

**Comment by w-vi** [comment]
Unfortunately not yet, there is a ongoing discussion (https://github.com/apiaryio/mson/issues/43) but nothing has been implemented.

Related question: https://github.com/apiaryio/mson/issues/72

Closing this one in favor of others.
