### ISSUE TITLE
Support for scopes

### ISSUE THREAD

**Issue by gjtorikian** [apiaryio/api-blueprint#36]
Many RESTful APIs support scopes for calls. In other words, you can't make a certain request or perform an action unless a client has been granted a certain scope. For example, using the "Gist Fox API,", you might need `gist_write` access to Edit a Gist.

Is there any support planned for surfacing this sort of information?

**Comment by zdne** [comment]
Closing as duplicate to #11. 

See (and comment on) RFCs https://github.com/apiaryio/api-blueprint/issues/11#issue-18055746
