### ISSUE TITLE
Type of array enums not validating

### ISSUE THREAD

**Issue by Ramblurr** [apiaryio/api-blueprint#360]
If I have a query parameter line like so:

```
    + filter[documents][state][]: `['DRAFT', 'FINISHED]` (array[string], optional) - Find documents matching the states provided.
        + Members
            + DRAFT
            + IN_PROGRESS
            + CLOSED
```

Then drafter complains:

```
Warning: the example value '['DRAFT', 'FINISHED]' of parameter 'filter[documents][state][]' is not in its list of expected values
```

I can't find in the spec any mention of typed arrays like this. Is this a supported feature? What's the proper way to limit the types of an array?

**Comment by pksunkara** [comment]
@Ramblurr You have specified the type to be string, so the value becomes `['DRAFT', 'FINISHED']`  as string (not an array). Since this value is not found in the list you gave, this is valid warning.

**Comment by Ramblurr** [comment]
Thanks @pksunkara  What is the proper way to specify an array of strings, provide members, and an example?

**Comment by pksunkara** [comment]
You can try `DRAFT, FINISHED` instead of `` `['DRAFT', 'FINISHED']` ``

**Comment by kylef** [comment]
@Ramblurr Did Pavan's suggestion solve your problem?
