### ISSUE TITLE
Response objects inconsistent

### ISSUE THREAD

**Issue by SMillerDev** [apiaryio/api-blueprint#364]
Why almost every other object allows for a description (including requests) responses do not.
This makes it impossible to list explanations for errors in a way like is done [here](https://sample-threes.readme.io/docs/errors).
I think for both consistency and usability this is something that should be addressed.

_Reference for thinking this is not supported: [https://apiblueprint.org/documentation/specification.html#def-response-section](https://apiblueprint.org/documentation/specification.html#def-response-section)_

**Comment by w-vi** [comment]
It is supported, at least that's what I read from the spec. As the Response inherits from [Payload Section](https://apiblueprint.org/documentation/specification.html#def-payload-section)

**Comment by SMillerDev** [comment]
Just tried again and it seems there was an issue in my first try. It does actually work. Maybe the documentation can be less ambiguous about it though?

**Comment by kylef** [comment]
@SMillerDev Do you have any particular ideas on how to make this clearer in the docs?

The specification for the section structure at https://apiblueprint.org/documentation/specification.html#def-section-structure declares an example including descriptions.
