### ISSUE TITLE
How render/display information that some attributte can be null?

### ISSUE THREAD

**Issue by webmato** [apiaryio/api-blueprint#366]
The issue how do document `null` value of some attribute we have   [solved](https://github.com/apiaryio/mson/issues/26).
```
- myAtrribute (object, nullable, required) - 'Lorem ipsum'
```

**But I see another issue - how this `nullable` attribute is (not) rendered in Apiary**.  The reader of this documentation does not have any information that this attribute can be `null` and I don't think that description field is a solution.

I have tried this but it generates error:
```
- myAtrribute: null (object, nullable, required) - 'Lorem ipsum'
```
this generates semantic error: `'object' with value definition. You should use type definition without value eg. '- key (object)'`

**Comment by w-vi** [comment]
`- myAtrribute (object, nullable, required) - 'Lorem ipsum'` should suffice, if you don't provide an example value the `null` value will be used. If that is what you are asking for.

**Comment by webmato** [comment]
Yes for passing tests it is enough, but a person how just read this documentation does have no idea that this attribute can be `null`. Many times I had to explain to my customers or colleague that some particular attribute can be `null`` - they always expect some real value not `null`. 

See this my of Apiary example.
![vystrizek](https://cloud.githubusercontent.com/assets/22371818/19888838/8834f318-a031-11e6-9e6a-cdb6e9f6586c.JPG)

The issue is that many people just expect they will always receive: 
```javascript
myAtrribute: {
   name: 'myCoolName',
   success: true,
}
```
and if they get: 
```javascript
myAtrribute: null
```
they reports it as an error. 

In the rendered documentation should be some info that some attribute can be `null`.

**Comment by w-vi** [comment]
I see what you mean now. Thanks for reporting it.

**Comment by kylef** [comment]
Apiary lists what is shown in rendered documentation from MSON at https://github.com/apiaryio/attributes-kit/blob/master/STATUS.md#35-type-definition and you can see that nullable is not supported yet.

**Comment by webmato** [comment]
ok 👍  good to know. Apairy/Apiblueprint is huge project with so many pieces, repositories and tools, it is sometimes hard to find relevant info  😄  Thaks
