### ISSUE TITLE
How to use the browser console mode in preview?

### ISSUE THREAD

**Issue by sailxjx** [apiaryio/api-blueprint#371]
As the document mentioned [here](https://help.apiary.io/tools/interactive-documentation/#browser-console), how can I send the request directly from `host`, without through the apiary proxy?

I use the apiary cli tool and `apiary preview --server` to host my documents.

**Comment by pksunkara** [comment]
You should be able to change the sever dropdown input in the console.

**Comment by sailxjx** [comment]
Sorry I can not find other options in my console, there is only 'Production' in the dropdown list
<img width="507" alt="2016-12-12 09 37 27" src="https://cloud.githubusercontent.com/assets/909853/21085574/b97c5578-c04e-11e6-8c8c-5c0c299a4dc0.png">

**Comment by kylef** [comment]
@sailxjx This feature isn't fully rolled out at the moment to all users at Apiary. Please make a support request to Apiary and they might be able to enable the feature for your account. You can ask in the in-app chat or via support@apiary.io.

I'm not entirely sure if `apiary preview` will work with the private console (Apiary support will be able to help you further than we can here) as this feature isn't API Blueprint specific.

Hope this helps.

**Comment by sailxjx** [comment]
@kylef Thanks, it helps
