### ISSUE TITLE
URI parameters section, required is default but i wantn't

### ISSUE THREAD

**Issue by killdada** [apiaryio/api-blueprint#374]
use drafter parse blueprint
![qq 20161228172719](https://cloud.githubusercontent.com/assets/16487810/21518645/e89e5f0a-cd22-11e6-82eb-39ae90db30df.png)

generated required = true  but wantn't

**Comment by pksunkara** [comment]
@killdada You need to do something like this:

```
+ Parameters

    + id (optional)
```
