### ISSUE TITLE
How can I represent `array[object]` attributes?

### ISSUE THREAD

**Issue by kyungmi** [apiaryio/api-blueprint#383]
I want to write document like below.
But It doesn't seem to be processed with Apiary editor in appropriate way.

```
+ Response 200 (application/json)

    Using `group_by` option

    + Attributes
        + result (array[object])
            + `book_id` (string) - book ID that is grouping annotations
            + `annotations` (array[Annotation]) - annotations in this book
        + `total_count` (number)

```

How do I write this kind of structure?

I attach screenshot of the preview window of Apiary Editor.

![screenshot](https://cloud.githubusercontent.com/assets/8926395/23255943/c71140fe-fa00-11e6-9c43-829b70ccf5a4.png)

**Comment by kylef** [comment]
You can't place key/value directory inside an array, you'd have to place it within an object as follows:

```apib
+ Response 200 (application/json)
    + Attributes
        + result (array[object])
            + (object)
                + `book_id` (string) - book ID that is grouping annotations
                + `annotations` (array[Annotation]) - annotations in this book
        + `total_count` (number)

## Data Structures
# Annotation (object)

+ some: thing
```

![screen shot 2017-02-23 at 11 02 46](https://cloud.githubusercontent.com/assets/44164/23256503/a4030424-f9b7-11e6-8041-972ae365a91e.png)

**Comment by kyungmi** [comment]
@kylef It is really helpful. Thank you so much :)
