### ISSUE TITLE
embedding fails for subdomains with '.' in it.

### ISSUE THREAD

**Issue by denizoguz** [apiaryio/api-blueprint#390]
if subdomain contains . in it, embedding fails with following error:

> {"statusCode":404,"message":"An error occurred, could not find the suite."}

You can reproduce the issue using following pen: http://codepen.io/denizoguz/pen/VbZKgV

**Comment by netmilk** [comment]
@denizoguz The subdomain in the Embed JS API shouldn't contain the "doc." part. Please refer to The Apiary Embedded Documentation [JS API reference](http://embed.apiary.io/quick-start.html) and the [help page](https://help.apiary.io/tools/embed/). Also, please keep in mind the Apiary Embedded documentation is part of the higher [subscription plans](https://apiary.io/plans). 

As long as this isn't an API Blueprint project related issue, I'm closing it for now. Should you have any further questions please reach out to the Apiary Support directly in the application (under the question mark icon in the main navigation).

![image](https://cloud.githubusercontent.com/assets/79609/24907068/dac8d132-1eba-11e7-83f2-399a8a733eb6.png)
