### ISSUE TITLE
Allow any object?

### ISSUE THREAD

**Issue by franklinyu** [apiaryio/api-blueprint#398]
How do I allow any object to be value of a key? such as

```json
{
  "prop": {"foo": 1, "bar": true}
}
```

I want to allow user to put any object as value of `"prop"`. If I do

```apib
+ prop: `{"a": 1}` (object)
```

It says this is invalid, because an object can't have value example.

Actually my use case would be `Map<String, Number>` instead of plain object (keys are not known in advance). I'm wondering whether API Blueprint is able to specify that.

**Comment by pksunkara** [comment]
@franklinyu Just do something like this.

```
+ prop (object)
```

It means, it can be any object.

**Comment by franklinyu** [comment]
Then it can't have any example. This hurts when it is actually *not* any object, just not able to express in current API Blueprint specification. I have to explain in the comments, which is not as loud as an example.

**Comment by pksunkara** [comment]
I don't understand. You said it can be any object and then you are saying it can't be any object? Can you please explain what exactly you are trying to do in a little more detail?

**Comment by franklinyu** [comment]
I want to specify that it need to be `Map<String, Number>`, but the key can be any string. For example,

```json
{
  "foo": 1,
  "bar": 2
}
```

is acceptable, but not

```json
{
  "string": "string",
  "boolean": true,
  "object": {
    "key": "val"
  }
}
```

AFAIK there is no way to specify this structure in API Blueprint, so I'm wondering whether I can just show a valid example to readers of my API.

**Comment by pksunkara** [comment]
You can do something like this:

```
+ (object)
    + *key* (number)
```

**Comment by franklinyu** [comment]
Not sure how that would work. Is that [Generic Named Type](https://apiblueprint.org/documentation/mson/specification.html#53-generic-named-type)? (I suddenly found that this issue belongs to MSON, but anyway.)

**Comment by pksunkara** [comment]
It is variable property name

**Comment by franklinyu** [comment]
Thank you. That's exactly what I need. However Apiary doesn't seem to support that:

```apib
+ Request
    + Attributes (object)
        + *key* (number)
```

and

```apib
+ Request
    + Attributes (object)
        + key (number)
```

looks the same in the generated documentation.

<sub>([documentation link for my own record](https://apiblueprint.org/documentation/mson/specification.html#322-variable-property-name))</sub>

**Comment by pksunkara** [comment]
Yes. It's not completely supported in apiary
