### ISSUE TITLE
Support Jetbrains Webstorm

### ISSUE THREAD

**Issue by ghostsquad** [apiaryio/api-blueprint#402]
It would be super awesome to have a plugin/support for Jetbrains Webstorm. If this isn't the right place for this suggestion, I'm happy to put it somewhere else.

**Comment by fgblomqvist** [comment]
If you do add this, it would be great if it wasn't just for Webstorm but also compatible with IntelliJ IDEA.

**Comment by kylef** [comment]
Merging this with https://github.com/apiaryio/api-blueprint/issues/386.
