### ISSUE TITLE
Referencing properties of a data structure in the document.

### ISSUE THREAD

**Issue by arn95** [apiaryio/api-blueprint#411]
Hi,

I opened a question on StackOverflow a while back but it didn't get much traction so I assume this feature does not exist. However, it would be so cool if it did!

So to summarize:

I want to reference properties inside of a declared data structure in order to reuse them later in various parts of the document where the actual content of the property might not be as memorable and it would be nice if it had a name. 

The first time I thought about it is HTTP return codes. If you want to standardize return codes throughout the document then you need to declare properties and refer to them but people make mistakes and a 201 is different from a 200 so a property named success inside a Http data structure would be very helpful.

Actual more detailed explanation with example: 
https://stackoverflow.com/questions/47849041/referencing-a-property-inside-a-defined-data-structure-in-api-blueprint-mson

**Comment by pksunkara** [comment]
This is not possible and there's no plan for this. You can create 3 different data structures for each status code and then use them individually. And then combine them together to get the major HTTPStatusCode data structure.
