### ISSUE TITLE
Apiary: problem with sidebar anchors (internal links)

### ISSUE THREAD

**Issue by leomp12** [apiaryio/api-blueprint#413]
Hello,
First of all, sorry to put this issue here, I could not found an repository for apiary.io site...
I'm having problems with anchors in the sidebar, it goes to wrong parts of the page.
Used to work fine, but the document got bigger and the problem appeared, is there anything that can be done to correct it?

Here is the API documentation:
https://ecomstore.docs.apiary.io/#
And here is the API Blueprint:
https://github.com/ecomclub/ecomplus-api-docs/blob/master/apiary.apib

Tanks!

**Comment by leomp12** [comment]
Example link:
https://ecomstore.docs.apiary.io/#reference/authentications
Should go to 'Authentications', but it goes to 'Your Store'

**Comment by char0n** [comment]
Hi @leomp12,

Actually when I open the link, it goes for me to `Authentication` section. Still...we know about this issue as it affects some of the generated documentations. This bug is also not 100% reproducible. We are currently working on solution that should solve this problem for good.

**Comment by leomp12** [comment]
Ok, thank you.
There is a public repository for documentation rendering at apiary.io?

**Comment by char0n** [comment]
@leomp12 nope, the documentation renderer on apiary.io is close-sourced.

**Comment by leomp12** [comment]
@char0n thank you!  I'll close the issue, maybe I try to solve with custom JS.
