### ISSUE TITLE
Unable to escape underscore

### ISSUE THREAD

**Issue by fgblomqvist** [apiaryio/api-blueprint#421]
Example
```
+ Request (application/json)
    + Attributes
        + api_key: `<API_KEY>` (string, required)
```

Gets parsed like this:
![screenshot from 2018-03-07 12-20-19](https://user-images.githubusercontent.com/649260/37116080-f39ff712-2201-11e8-88ef-d1ab4ac3f7d2.png)

(Dredd also reads it in the same way, so it is definitely the parser that is wrong)

**Comment by kylef** [comment]
You will need to escape the underscore, for example:

```apib
+ Request (application/json)
    + Attributes
        + `api_key`: `<API_KEY>` (string, required)
```

**Comment by fgblomqvist** [comment]
Ah, didn't realize that it was the first underscore that was causing the issue. Apiary should imo catch that as a semantic issue: "Attribute names that include underscores need to be escaped with backticks" or something along those lines.

**Comment by kylef** [comment]
I'm going to close this issue as it's tracked in https://github.com/apiaryio/api-blueprint/issues/210.
