### ISSUE TITLE
Post variables as FORM-DATA?

### ISSUE THREAD

**Issue by fh-thudson** [apiaryio/api-blueprint#424]
Hey guys,

I love apiary it looks 100 times better than swagger.  The only issue that I am having is I just post form data on endpoints.  I can't seem to understand how to tell apiary that it's not a JSON in the body of the post.  I would love for the attributes to come up just as it would for URI parameters.  I like how that looks.  I don't want just an empty body section on the endpoint because let's face it users aren't very intelligent.  If I can't do this I can just use swagger still and that works just fine.  

Please and thank you for any help I can receive. 

![image](https://user-images.githubusercontent.com/20419422/37346680-50635c16-26a6-11e8-95fc-4ea3158ffa41.png)

**Comment by fh-thudson** [comment]
It was a lug nut... Fixed it!

![image](https://user-images.githubusercontent.com/20419422/37347310-e52848e2-26a7-11e8-8bf6-98ad45298c4f.png)

**Comment by fh-thudson** [comment]
Is there any way I can get that Authorization "Token" to be dynamic and stored from the 1st authorization endpoint?

**Comment by kylef** [comment]
Hi @fh-thudson, we do plan to bring MSON to both headers and parameters (currently tracked in https://github.com/apiaryio/api-blueprint-rfcs/pull/3).

As for the question regarding storing an authorization token. Headers in API Blueprint are purely example, the values are not fixed. As for storing headers between requests it sounds like a feature request for any tooling you are using. For example, the Apiary console allows you to mark a header as persistent and then it will be applied to every request made via the console (https://help.apiary.io/tools/interactive-documentation/#persistent-http-headers-in-console).

Does that answer your questions?
