### ISSUE TITLE
Can we use apiary to define SOAP API?

### ISSUE THREAD

**Issue by sajantha** [apiaryio/api-blueprint#427]
can we define a soap API having message structure in below format IN Apiary
<SOAP-ENV:Envelope xmlns:SOAP-ENV = "http://schemas.xmlsoap.org/soap/envelope/"
 

  <SOAP-ENV:Header>
     ...
     ...
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
     ...
     ...
     <SOAP-ENV:Fault>
        ...
        ...
     </SOAP-ENV:Fault>
     ...
  </SOAP-ENV:Body>
</SOAP_ENV:Envelope>

**Comment by kylef** [comment]
Hi @sajantha,

API Blueprint doesn't limit what you can place inside a message body. You can place XML if you wish, for example:

```apib
FORMAT: 1A

# My SOAP API

## GET /soap/envelope

+ Response 200 (application/xml)

        <SOAP-ENV:Envelope xmlns:SOAP-ENV = "http://schemas.xmlsoap.org/soap/envelope"
        ... 
        </SOAP_ENV:Envelope>


```
