### ISSUE TITLE
will there ever be inline comments?

### ISSUE THREAD

**Issue by andylaci** [apiaryio/api-blueprint#429]
hello, I was working on 1 project with my colleges and we consider to have possibility to add description directly to request fields, regular inline comment `// comment`, but blueprint of course reports errors, is it possible somehow?

**Comment by kylef** [comment]
Hi @andylaci,

This is a tracked feature in #139 about supporting comments. Would you be able perhaps elaborate on adding comments to the request fields in #139. Perhaps showing an example of what you are looking to comment would be great.

I'm going to close this issue as it's tracked in #139, thanks for reporting and sharing more insight into the type of comments you're looking for.
