### ISSUE TITLE
questions 

### ISSUE THREAD

**Issue by dannySanchez1212** [apiaryio/api-blueprint#432]
Undefined variable: api (View: C:\xampp\htdocs\Api CounterPath\vendor\m165437\laravel-blueprint-docs\resources\views\navigation.blade.php) (View: C:\xampp\htdocs\ApiCounterPath\vendor\m165437\laravel-blueprint-docs\resources\views\navigation.blade.php)

Is it a documentation of an already completed application if you can do this documentation only with the .apib file?

since I do not have the project only the previous documentation on the web?

**Comment by kylef** [comment]
Hi @dannySanchez1212,

This questions appears to be something related to a third-party Laravel support and I don't think that is it relevant to the API Blueprint issue tracker. I'd recommend reaching out to the author/maintainer of the particular code you are using for your query.
