### ISSUE TITLE
"Show json schema" link disappears

### ISSUE THREAD

**Issue by maxiwheat** [apiaryio/api-blueprint#438]
For our API, we gave an example body and also a JSON schema for this resource:

https://cyberimpactapiv4.docs.apiary.io/#reference/ressources/batches/add-a-batch

Sometimes, the link to show the JSON schema on the right disappears for no reason. Try changing "raw" in the dropdown menu for something else (or just re-selecting raw over and over) and then returning to raw, the link to show the json schema then disappears, that particular dropdown seems to cause the issue.

**Comment by kylef** [comment]
Hi, this problem has been solved in our new ApiaryUI renderer. Please check out https://blog.apiary.io/ApiaryUI for more information.

If you have any further bug reports that are specific to Apiary rendered documentation please reach out to Apiary support. This repository and issue tracker is tracking the API Blueprint specification.
