### ISSUE TITLE
Add schema to the tutorial

### ISSUE THREAD

**Issue by rurounijones** [apiaryio/api-blueprint#44]
I think it would be very beneficial to add a JSON Schema to the tutorial (https://github.com/apiaryio/api-blueprint/blob/master/Tutorial.md) to show how it can be used. Possibleyone of the last steps? (an "Advanced" section maybe?)

**Comment by philsturgeon** [comment]
It would be link to some of this other data here:

https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#6-schema-section

I read the documentation and still had _no_ idea how to work with JSON Schema in API Blueprint, which seems like what its for.

**Comment by zdne** [comment]
I will fix it ASAP.

**Comment by zdne** [comment]
Is this what you were looking for ?

https://github.com/apiaryio/api-blueprint/blob/zdne/schema-clarification/API%20Blueprint%20Specification.md#def-schema-section 

or is it more about how is schema used inside Apiary  (where / for what)?

**Comment by johntron** [comment]
+1 this is great @zdne! Do you know if Apiary actually validates bodies using the provided schema? It doesn't appear to in the console, but maybe my blueprint is wrong:

```
### Add something [POST /collection/{id}]

+ Parameters
    + id (string) - Collection ID where new resource will be added

+ Request (application/json)

    + Body
    
            {
              "name": "My new resource"
            }
    
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                    "name": { 
                        "type": "string",
                        "description": "Name of resource"
                    }
                },
                "required": ["id"]
            }

+ Response 200 (application/json)

        {
            "id": "2beec1718b4399643e00987d321e8af7"
        }
```

Maybe the blueprint above could be added to a new "Advanced" section in [Tutorial.md](https://github.com/apiaryio/api-blueprint/blob/master/Tutorial.md)?

**Comment by zdne** [comment]
We have created a new "advanced" tutorial that should cover the schema topic. Check out [here] (https://github.com/apiaryio/api-blueprint/blob/master/Advanced%20Tutorial.md)
