### ISSUE TITLE
'Required' popover has broken text wrapping

### ISSUE THREAD

**Issue by nathanjliu** [apiaryio/api-blueprint#440]
The 'required' label in the list of parameters wraps at the end of the popover. Changing the size of the window or zooming in or out on the page does not fix it.

![image](https://i.imgur.com/n3XMmJQ.png)

Tested on Chrome 72.0.3626.17 and Safari 12.0.1, both on macOS 10.14.1

**Comment by char0n** [comment]
Thank you, we have a look at it.

**Comment by kylef** [comment]
Hi, this problem has been solved in our new ApiaryUI renderer. Please check out https://blog.apiary.io/ApiaryUI for more information.

If you have any further bug reports that are specific to Apiary rendered documentation please reach out to Apiary support. This repository and issue tracker is tracking the API Blueprint specification.
