### ISSUE TITLE
Links with quotes don't work

### ISSUE THREAD

**Issue by gera-wolkow** [apiaryio/api-blueprint#446]
URLs don't work when contain quotes

Headers like this:

> ### List "All" Questions

are not opened

Example:
https://yryndin.docs.apiary.io/reference/0/questions-collection/list-%22all%22-questions

**Comment by patricksmms** [comment]
Hi @gera-wolkow, thanks for reporting this issue!

We have covered this and many other scenarios on the new [ApiaryUI](https://help.apiary.io/tools/interactive-documentation-v4/).

Is this affecting any of your API documents?

**Comment by gera-wolkow** [comment]
Hi @patricksmms 
Yes, it's affecting huge number of my private documents. Thanks for the V4 idea. It can be the solution! 
Do U have ability to fix it in V3?

**Comment by patricksmms** [comment]
@gera-wolkow, yes. I'll let you know once the fix is in v3.

**Comment by patricksmms** [comment]
Hi @gera-wolkow, I just deployed the fix to this issue in v3. Thanks again for reporting it.

**Comment by char0n** [comment]
@patricksmms nice ;]

**Comment by gera-wolkow** [comment]
Thanks a lot!
