### ISSUE TITLE
Allow actions with custom URLs to use parameters from parent resource

### ISSUE THREAD

**Issue by alexkreidler** [apiaryio/api-blueprint#452]
I have the following API Blueprint:
```apib
## Run Information [/processors/{id}/runs/{runID}]
Provides information about all the Runs on a given processor.

+ Parameters
    + id (string) - The processor ID
    + runID (string) - The run ID


### Retrieve One Run [GET]
+ Response 200 (application/json)
    + Attributes (Run)


### Configure [POST /processors/{id}/runs/{runID}/configure]
+ Response 200 (application/json)
    + Attributes (Run)
```

I want the `Parameters` from my "Run Information" `ResourceGroup` to cascade down to my Configure action, but instead, I get this:

![image](https://user-images.githubusercontent.com/11166947/70927719-85c9c000-1ffd-11ea-9223-0583b14cf7a9.png)

So I need to add the `+ Parameters` section to the Action itself, causing duplication.

Additionally, if we were able to use relative URIs (#451), then I wouldn't even have to write  `/processors/{id}/runs/{runID}/configure`, I'd just write `./configure`. Once this Parameters cascade issue is fixed, then it'd be super easy to add new actions without duplicating anything.

**Comment by kylef** [comment]
I think this is a bug in Aglio, you may want to file a bug with that software instead.

Other [reference documentation renderers](https://help.apiary.io/tools/interactive-documentation-v4/) offer this:

![2020-09-28-120846_733x630_scrot](https://user-images.githubusercontent.com/44164/94425261-8a71f600-0183-11eb-803e-9dc2ddd7e836.png)
