### ISSUE TITLE
Invalid value for 'boolean' type in nested request body on apiary.io

### ISSUE THREAD

**Issue by ir-fuel** [apiaryio/api-blueprint#453]
The following gives me a warning for the `subscription` attribute, but not for the `testBool` attribute, and I have no idea why

```
## Collection [/user]

### Update user profile [PATCH /user/{id}]

+ Parameters
    + id (string) - Id of the user

+ Request 

    + Attributes (object)
        + testBool (boolean)
        + arr (array[object])
            + id (string)
            + subscription (boolean)

    + Body
    
            {
            }

+ Response 204


```

**Comment by kylef** [comment]
The syntax for placing items in array is as follows:

```apib
+ Attributes (array)
    + hello (string)
    + true (boolean)
    + (object)
        + key: value
```

Which equates to the following structure in JSON:

```json
[
  "hello",
  true
]
```

The line from your API Blueprint `+ subscription (boolean)` is stating that you want a boolean, with the value "subscription" inside the array. As "subscription" is not a valid boolean (it is not `true` or `false`, the warning is emitted).

Instead, I think you are intending to wrap these array values in an object, for example an `object` with a key `id` and another with `subscription`. To do this in MSON you would write the following:

```apib
+ Attributes
    + arr (array[object])
        + (object)
            + id (string)
            + subscription (boolean)
```
