### ISSUE TITLE
Nested data structures don't render correctly

### ISSUE THREAD

**Issue by ir-fuel** [apiaryio/api-blueprint#454]
This is the document
```
## Data structures

### Location(object)
    + latitude (number,required)
    + longitude (number,required)

### Result(object)
    + id (string,required)
    + location (Location,required)

## Collection [/user]

### Update user profile 2 [PATCH /user2/{id}]

+ Parameters
    + id (string) - Id of the user

+ Request 

    + Attributes (object)
        + testBool (boolean)
        + arr (array[Result])

    + Body
    
            {
            }

+ Response 204
```

This is what it looks like when rendering this:

![Screenshot 2019-12-23 at 09 24 58](https://user-images.githubusercontent.com/1573715/71345612-1f492280-2566-11ea-904f-67d9dd674104.jpg)

As you can see the nested `Location` data structure is not shown correctly

**Comment by kylef** [comment]
The indentation of the items is incorrect and thus it is being treated as a description block (code block specifically), this removing indentation of the resuable data structures, for example:

```apib
### Location(object)

+ latitude (number,required)
+ longitude (number,required)

### Result(object)

+ id (string,required)
+ location (Location,required)
```

**Comment by ir-fuel** [comment]
Right. I discovered this too in the mean time but forgot about this ticket ...
