### ISSUE TITLE
Provide example generated docs

### ISSUE THREAD

**Issue by mariusa** [apiaryio/api-blueprint#458]
As a developer looking for an API docs tool, I'd like to see examples of docs generated with this tool.

These are useless, as they look like the source:
https://apiblueprint.org/documentation/examples/gist-fox-api.html

We want to see the results.

README links to tesla-api, which links to 
https://tesla-api.timdorr.com/api-basics/vehicles
which is a great example of what we're looking for. However, it says Powered by GitBook (not api-blueprint)

What are some API docs generated with this tool?

**Comment by kylef** [comment]
API Blueprint is a description format for describing web APIs, it in itself is not a tool for generating rendered HTML API Documentation.

There are numerous pieces of software around in the community for generating documentation from API Blueprint's, we maintain a list of the ones we are aware of at https://apiblueprint.org/tools.html#renderers. Each of those should provide examples in their documentation.

[ApiaryUI](https://blog.apiary.io/ApiaryUI) has an example at https://pollsapi.docs.apiary.io/.

**Comment by mariusa** [comment]
Thanks for clarification

**Comment by kylef** [comment]
No problem, we can leave this issue open if you would like. I think we could explore adding a link to view a HTML version of these examples elsewhere with some of the renderers to help people compare. Just wanted to give you the information upfront.
