### ISSUE TITLE
Python2 versus Python3

### ISSUE THREAD

**Issue by joshwolff1** [apiaryio/api-blueprint#459]
Apiary documentation appears to only provide support for Python2. 

Python2 is deprecated.

Is support for Python3 available?

Sample: https://pandurangpatil.docs.apiary.io/#introduction/description-of-usual-server-responses

**Comment by joshwolff1** [comment]
An example from the documentation I linked

```

from urllib2 import Request, urlopen

request = Request('http://sample.pandurangpatil.com/users(?since,limit)')

response_body = urlopen(request).read()
print response_body
```

This is Python2 and the code is not portable. It is not a great user experience for my users, who primarily use Python3, to have to convert and debug Python2 code.

**Comment by kylef** [comment]
The code examples on [Apiary Interactive Documentation v4](https://blog.apiary.io/ApiaryUI) will support Python 3, [you can check out one of the examples](https://pollsapi.docs.apiary.io). User's will need to opt-in to the newer version in the API Project settings.

**Comment by joshwolff1** [comment]
Thank you
