### ISSUE TITLE
API v4 Bug: Delete Body Unused

### ISSUE THREAD

**Issue by joshwolff1** [apiaryio/api-blueprint#462]
Hello,

It looks like the values are not set in the DELETE method but are set elsewhere.

See here: In the DELETE method code, the data parameter in the function call is never used (and thus the values variable is not either), whereas they are used in the PATCH method (and the other methods).

<img width="1440" alt="Screen Shot 2020-06-12 at 11 23 15 PM" src="https://user-images.githubusercontent.com/28893844/84561781-2a566180-ad04-11ea-8032-e842061154a5.png">

In the PATCH method code (and for other methods), the request is composed as expected.

<img width="1429" alt="Screen Shot 2020-06-12 at 11 23 06 PM" src="https://user-images.githubusercontent.com/28893844/84561776-1f033600-ad04-11ea-9d08-cbc069f742b1.png">

**Comment by Mnau-mnau** [comment]
@joshwolff1 This issue was fixed for python and released in [v4 0.30.1](https://github.com/apiaryio/documentation-service/releases/tag/v0.30.1)

**Comment by joshwolff1** [comment]
Thank you for the prompt fix.

I hate to re-open this, but I just noticed that GET has the same issue. I didn't notice this before

<img width="1417" alt="Screen Shot 2020-06-17 at 3 59 36 PM" src="https://user-images.githubusercontent.com/28893844/84959168-ac9fa680-b0b3-11ea-8a81-06dc30d2294d.png">
