### ISSUE TITLE
API v4 Bug: Get body unused

### ISSUE THREAD

**Issue by joshwolff1** [apiaryio/api-blueprint#463]
Thank you for the prompt fix in #462

I hate to add a similar issue, but I just noticed that GET has the same issue. I didn't notice this before

<img width="1417" alt="Screen Shot 2020-06-17 at 3 59 36 PM" src="https://user-images.githubusercontent.com/28893844/84959168-ac9fa680-b0b3-11ea-8a81-06dc30d2294d.png">

_Originally posted by @joshwolff1 in https://github.com/apiaryio/api-blueprint/issues/462#issuecomment-645669958_

**Comment by joshwolff1** [comment]
Any update on this?

**Comment by opichals** [comment]
@joshwolff1 This was fixed and released in around October 2020.
