### ISSUE TITLE
Is api-blueprint still alive?

### ISSUE THREAD

**Issue by lyssar** [apiaryio/api-blueprint#467]
Hi there!
I would like to know if api-blueprint is considered as "dead". Last commit is form 2019 and if so please mark this as so :)

Kind regards

**Comment by lyssar** [comment]
Seems that this project was abandoned... no response in nearly a month.

**Comment by monzilnepali** [comment]
What are other alternatives to the API blueprint?

**Comment by arlukin** [comment]
Looks like things still happen in 
https://github.com/bukalapak/snowboard

**Comment by kiriakos** [comment]
https://github.com/bukalapak/snowboard still seems to be active

**Comment by gayanhewa** [comment]
> What are other alternatives to the API blueprint?

OpenAPI Spec v3

**Comment by abtris** [comment]
Project has no active maintainers available.
