### ISSUE TITLE
Traits

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint#47]
Introducing the API Blueprint Object Trait. Addressing following milestones:

- #11 Authentication
- #17 Referenced HTTP headers
- #19 Referenced Payloads
- #24 Global query URI parameter
- #36 Support for Scopes
- #38 Support for Specific Metadata

Full implementation of traits assume following issues are implemented:

- #25 Message-body Parameters Description
- #26 Parametric Headers Description
- #28 Nested Parameters

## What is a Trait
Trait is a quality or characteristic of an API Blueprint object (hereafter just *object*). At the moment the following sections of API Blueprint are recognized as API Blueprint object:

- API 
- Resource Group
- Resource
- Resource Model
- Action
- Request
- Response
- Parameter

Traits can be used add additional semantics or a set of characteristics to an object.

### Semantic Trait
A semantic traits adds a semantic meaning to an object.

Definition of a semantic trait:

    # My API
    + Trait A ... Object Quality "A"

Referencing a defined trait:
    
    ## Resource 1 [/1]
    + Traits
        + [A][]

In-place definition & use of a semantic trait:

    ## Resource 1 [/1]
    + Traits
        + A ... Object Quality "A"

NOTE: Traits defined in-place cannot be referenced later
    
An object can reference multiple traits:

    ## Resource 1 [/1]
    + Traits
        + [A][]
        + [B][]
        + C ... Object Quality "C"
        + Type = `safe`

### Characteristic Trait
In addition to its semantic meaning a trait can also express certain characteristic of object's [payload(s)](https://github.com/apiaryio/api-blueprint/blob/1B/Glossary%20of%20Terms.md#def-payload). 

Where payload characteristic is one of:

- parameter characteristic 
- property characteristic (new in Format 1B)
- [request | response] header characteristic
- body characteristic 
- schema characteristic 

For example:

    # My API
    + Trait Color
        + Response Headers
            + X-Resource-Color (string, `red`) ... Color of the resource.
    
    ## Resource 1 [/1]
    + Traits
        + [Color][]

One trait can also represent a set of object characteristics:

    # My API
    + Trait Art
        + Headers
            + X-Resource-Color (optional, string, `red`) ... Color of the resource

        + Properties
            + size = `42` (number) ... The size of an object
    
    ## Resource 1 [/1]
    + Traits
        + [Art][]

---

For more examples see https://gist.github.com/zdne/01e287fe18d232672d43

**Comment by itsjamie** [comment]
For those who come and read this, I'm about to test, but I think you could solve the issue of needing to duplicate it by using a tool such as https://github.com/jamesramsay/hercule

**Comment by andrewelkins** [comment]
That looks excellent

**Comment by itsjamie** [comment]
I'm hoping Traits becomes a slightly more supported version inside Blueprint. I believe this spec above that's being outlined means I could define a Trait that outlines all the various sub-aspects of a resource. Meaning, I could say that a resource has the Trait "Protected" which means that a access_token is required, one possible response from the resource is now a 401 Unauthorized.. etc...

**Comment by zdne** [comment]
Hey @itsjamie we are preparing a dedicated support for authentication. As soon as we will roll out #25 I will update this and #11  accordingly

**Comment by wyattjoh** [comment]
Any update on the progress on this? Our team uses api-blueprint exclusively for our documenting needs. We also have developed several code generators based on it, and could really use support for Traits (specifically, for scopes, which requires Traits).

**Comment by zdne** [comment]
@wyattjoh the support for authentication scopes is coming soon, I will share an update on this as soon as we will be done with the proposal. cc @pksunkara

**Comment by XiaoxiaoLi** [comment]
Any updates on this? This is really useful! Thanks!

**Comment by DataGreed** [comment]
With all respect guys, the project seems to be dead or very slow moving, i've switched to RAML.

**Comment by pksunkara** [comment]
@DataGreed Have you looked at the latest feature we are working on called [MSON](https://github.com/apiaryio/mson)? You can use it do a lot of things as shown in [here](https://github.com/apiaryio/api-blueprint/blob/master/examples/08.%20Attributes.md), [here](https://github.com/apiaryio/api-blueprint/blob/master/examples/09.%20Advanced%20Attributes.md) and [here](https://github.com/apiaryio/api-blueprint/blob/master/examples/10.%20Data%20Structures.md).

It is currently in beta and we are working hard on releasing it completely so that we can use it at a lot of other places in the Blueprint.

**Comment by netmikey** [comment]
What's going on, guys? "Working on it" for 2 years and then "status (6): Cancelled"? Ppl seem to really like api-blueprint but right now, it looks like a dying project - please tell me I'm wrong!

**Comment by pksunkara** [comment]
Hey @netmikey, This is going to be superseded by [MSON](https://github.com/apiaryio/mson) which is much much better. @zdne will give a full update soon.

**Comment by netmikey** [comment]
That was the piece of info missing on this issue thread ;) Thanks @pksunkara !

**Comment by zdne** [comment]
@netmikey it is not dying it all! Actually blueprint is doing better than ever. Spoiler: We have a big announcement coming next week and in the weeks to follow. It is just this issue is not going to happen as proposed here, but there are / will be features to address this functionality.

**Comment by zdne** [comment]
As hinted before the some of the features proposed in this issue were already implemented and released ( #25 ) some other are in making ( #11 and #286 ). 

Please see the recently published API Blueprint [roadmap](https://github.com/apiaryio/api-blueprint/wiki/Roadmap) for the planned features. Check [this blog post](http://blog.apiary.io/2015/12/17/API-Blueprint-Future/) for more detailed explanation of where the API Blueprint is heading. 

Thanks you!
