### ISSUE TITLE
API Blueprint on GitHub as a first-class citizen

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/api-blueprint#52]
Just an idea.

Now all blueprint files are superset of [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown), so they're obviously quite well displayed on GitHub out of the box.

However, if direct support for API Blueprint was added to [github/markup](https://github.com/github/markup), it would be possible to display blueprint-specific parts (such as endpoints, etc.) nicer than now and blueprints would be even more something like first-class citizens here on GitHub.

Possible problems:

- blueprint files would probably need to have a different extension, because parsers in `github/markup` are most likely binded by extensions and `.md` are already binded to the pure Markdown parser (and having a different extension undermines some of the pros of being fully compatible with Markdown)
- the output would have to fit within [allowed HTML elements](https://github.com/github/markup#html-sanitization), so probably no rich styling could apply anyway :-(

Another idea I came up with is to ask GitHub whether they wouldn't like to bake the direct support in themselves (maybe after the API Blueprint earns notable traction). Then it could be implemented in a similar way as [GeoJSON](https://github.com/blog/1528-there-s-a-map-for-that) or [3D objects](https://github.com/blog/1465-stl-file-viewing), I suppose.

**Comment by monsendag** [comment]
How about .apib.md? That would be parsed as markdown by default, but can be detected as api blueprint by supporting parsers.

**Comment by zdne** [comment]
We would still like GitHub to render blueprints correctly. @danielgtaylor to do some research on this

**Comment by monsendag** [comment]
I understand. I still think that the extension should be suffixed by .md. as it allows for a more graceful degradation.

**Comment by zdne** [comment]
As @danielgtaylor pointed out to me offline we may start with https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language I consider adding `.md` as the last resort option. 

Or precisely I would go for it if we should fail this time (hope not :)

**Comment by danielgtaylor** [comment]
I've now opened github/linguist#2363 to add support for recognizing and highlighting `.apib` files on GitHub.

**Comment by zdne** [comment]
:+1:

**Comment by pksunkara** [comment]
API Blueprint is now first-class citizen on Github.

**Comment by zdne** [comment]
@pksunkara we haven't a) announced this yet and b) this issue was more about rendering the blueprint  (not just syntax highlighting). 

Either way OK to leave it as closed. I will update this once we announce it.

**Comment by honzajavorek** [comment]
Yay! :+1: :octocat:
