### ISSUE TITLE
Support for multiline syntax header ?

### ISSUE THREAD

**Issue by ludofleury** [apiaryio/api-blueprint#60]
Hey,
_I'm not sure if we can use the issue tracker here for improvement request. (sorry)_

I have a case where I've got many informations for a http header, i.e. the `Link` http header.

In this case, to improve readability in the edition mode, preview or raw display, it would be really nice if it can support multiline.

```
+ Headers
    Link: </uri>;
                rel="http://myschema.org/relation/resource";
                title="My title",
          </uri2>;
                rel="http://myschema.org/relation/resource2";
                title="My title 2",
          </uri3>;
                rel="http://myschema.org/relation/resource3";
                title="My title 3",   
```

At the moment, everything is inlined and it's really annoying. 
Thank you for the awesome work.

**Comment by zdne** [comment]
RFC proposal of syntax addressing this issue: https://github.com/apiaryio/api-blueprint-rfcs/pull/3. 

Please track and comment on the RFC.

Thank you!
