### ISSUE TITLE
Java binding for snowcrash

### ISSUE THREAD

**Issue by outofcoffee** [apiaryio/api-blueprint#65]
Hi folks,

I'd be very keen to contribute to a Java binding for snowcrash or otherwise assist with a Java-based Markdown Blueprint -> AST parser. Having read around, it seems like building a parser based on code that's not Sundown is not the way to go, given the API Blueprint extensions to that codebase, so it would seem a pure Java toolchain is out of the question.

Having read https://github.com/apiaryio/snowcrash/wiki/Writing-a-binding I have found that there isn't enough for me to make a start on a Java binding, so I would appreciate someone providing some architectural guidance or suggestions about how to do this.

Full disclosure: I'm the author of the open source Java Mock Server mentioned on the apiblueprint.org site (https://bitbucket.org/outofcoffee/api-blueprint-mockserver) and would ideally like to use the Java parser to support some of the proposed features in that project.

Thoughts/comments welcome.

All the best,

Pete

**Comment by anshumandas** [comment]
attempted to parse MSON using PegDown a pure Java parser. Tested with most files in mson-zoo.
Code is here https://github.com/anshumandas/mson-parser for those interested.
As expressed above it is quite tedious approach to create a full parser but can surely be done.

**Comment by zdne** [comment]
@anshumandas yay! That looks interesting! Is ti parsing just single MSON objects or whole sets of data structures (named types). 

What is the output from it? Would you care to elaborate bit on it in the project's README ? 

Thanks for sharing!

**Comment by anshumandas** [comment]
It parses most samples in mson-zoo project.

It should parse multiple object blocks, but needs testing.

Currently only the nested list structures.
The output is my own MSONNode structure but it was more to check feasibility so did not use the Java binding AST in the first attempt to reduce learning curve. However this structure can be mapped to any other using the serialiser that uses the visitor pattern. Or else we can rewrite to directly use the AST instead.
