### ISSUE TITLE
Resources Relations

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint#88]
Expressing relations between resources through available actions (affordances). 

Currently a resource can define only actions defined on the respective resource. 
However, in reality, a resource may afford an actions that are not limited to the resource itself. 

###  Inline Action

In-place definition of another Resource. 
This section would follow standard rules for 
[Action Sections](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-action-section). 
With the exception that a different URI may be used. 
Defining an in-line action does not create a new API Blueprint Resource.

```md
# Task [/tasks/{id}]

+ Parameters
    + id

## Retrieve Task [GET]

+ Response 200

        { ... }

## Delete Task [DELETE]

+ Response 204

## Create New Task [POST /tasks]

+ Request

        { ... }

+ Response 200

        { ... }

## List All Tasks [GET /tasks{?parent,group_name,status,paused,priority}]

+ Parameters
    + parent
    + group_name
    + status
    + paused
    + priority

+ Response 200

        { ... }
```

###  Relation Identifiers

Optionally it SHOULD be possible to specify additional [link relation types](https://tools.ietf.org/html/rfc5988#section-4) as specified in the RFC 5988.

The syntax should be:

```md
+ Relation: <link relation identifier>
```

For example:

```md
# Task [/tasks/{id}]

+ Parameters
    + id

## Retrieve Task [GET]

+ Relation: task
+ Response 200

        { ... }

## Delete Task [DELETE]

+ Relation: delete
+ Response 204

## Create New Task [POST /tasks]

+ Relation: create
+ Request

        { ... }

+ Response 200

        { ... }

## List All Tasks [GET /tasks{?parent,group_name,status,paused,priority}]

+ Relation: list
+ Parameters
    + parent
    + group_name
    + status
    + paused
    + priority

+ Response 200

        { ... }
```

---

Update: Referencing another actions is not planned at the moment

### ~~Referencing Another Resource's Action~~
~~Affording another Resource action on this resource. Such a section would not have any other content except its definition.~~

```md
## User [/users/{id}]
### List [GET]
+ Response 200

        ...

## Post [/posts/{id}]
### Retrieve [GET]
+ Response 200

        ...

### Author: [User.List][]
```

**Comment by fosrias** [comment]
@zdne Just to be clear. Is this addressing the following scenario:

```
# Tasks 

## List Tasks [GET /tasks{?parent,group_name,status,paused,priority}] 
+ parameters
    + parent
    + group_name
    + status
    + paused
    + priority

+ response 200

        { ... }

## Create a Task [POST /tasks ]
+ response 201

**Comment by zdne** [comment]
@fosrias not exactly, you still have to have a top-level resource defined `Tasks` in this case. 

e.g. `# Tasks [/tasks]`, not what you are describing is already possible: 

```
# Tasks [/tasks{?parent,group_name,status,paused,priority}]
## List Tasks [GET] 
+ parameters
    + parent
    + group_name
    + status
    + paused
    + priority

+ response 200

        { ... }

## Create a Task [POST]
+ response 201
```

**Comment by zdne** [comment]
@fosrias 

This would be a better example, however I would still recommend defining `Tasks` and `Task` as two separate resource (collection of elements and one element): 

```md
# Task [/tasks/{id}]

+ Parameters
    + id

## Retrieve Task [GET]

+ Response 200

        { ... }

## Delete Task [DELETE]

+ Response 204

## Create New Task [POST /task]

+ Request

        { ... }

+ Response 200

        { ... }

## List All Tasks [GET /tasks{?parent,group_name,status,paused,priority}]

+ Parameters
    + parent
    + group_name
    + status
    + paused
    + priority

+ Response 200

        { ... }

```

**Comment by fosrias** [comment]
@zdne Concur on the separate resources. Probably was not paying close
enough attention. Will you be able to have a path on the resource element
and then override it if you want on an action under the resources. Seems it
should work that way so that you only modify actions if necessary. More DRY.

**Comment by pksunkara** [comment]
> Defining an in-line action does not create a new API Blueprint Resource.

What if I want it to be separate API Blueprint Resource? The use case here is that I want to have a Resource which contains only 1 action. So, instead of writing Resource header and Action header, I want to combine them both in a single line.

**Comment by zdne** [comment]
Both "inline actions":

```markdown
## Create New Task [POST /tasks]
```

and "action relation types":

```markdown
+ Relation: create
```

 are now supported in Apiary (as of 1A8). Please let us know how do you like these new features! 

Refer to: 

- [Action Section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-action-section)
- [Relation Section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-relation-section)
